Received: from CWXP265MB1702.GBRP265.PROD.OUTLOOK.COM (2603:10a6:401:5a::27)
 by CWLP265MB1699.GBRP265.PROD.OUTLOOK.COM with HTTPS via
 CWLP265CA0351.GBRP265.PROD.OUTLOOK.COM; Mon, 8 Oct 2018 09:11:11 +0000
Received: from LO2P265CA0173.GBRP265.PROD.OUTLOOK.COM (2603:10a6:600:a::17) by
 CWXP265MB1702.GBRP265.PROD.OUTLOOK.COM (2603:10a6:401:4a::17) with Microsoft
 SMTP Server (version=TLS1_2, cipher=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384) id
 15.20.1207.22; Mon, 8 Oct 2018 09:11:09 +0000
Received: from AM5EUR02FT065.eop-EUR02.prod.protection.outlook.com
 (2a01:111:f400:7e1e::206) by LO2P265CA0173.outlook.office365.com
 (2603:10a6:600:a::17) with Microsoft SMTP Server (version=TLS1_2,
 cipher=TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384) id 15.20.1185.22 via Frontend
 Transport; Mon, 8 Oct 2018 09:11:09 +0000
Authentication-Results: spf=softfail (sender IP is 163.1.154.218)
 smtp.mailfrom=pmbounces.feedback.doorbell.io;
 UniOxfordNexus.mail.onmicrosoft.com; dkim=fail (signature did not verify)
 header.d=feedback.doorbell.io;UniOxfordNexus.mail.onmicrosoft.com; dmarc=fail
 action=none header.from=feedback.doorbell.io;
Received-SPF: SoftFail (protection.outlook.com: domain of transitioning
 pmbounces.feedback.doorbell.io discourages use of 163.1.154.218 as permitted
 sender)
Received: from smtp.nexus.ox.ac.uk (163.1.154.218) by
 AM5EUR02FT065.mail.protection.outlook.com (10.152.9.25) with Microsoft SMTP
 Server (version=TLS1_0, cipher=TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA) id
 15.20.1228.17 via Frontend Transport; Mon, 8 Oct 2018 09:11:08 +0000
Received: from relay14.mail.ox.ac.uk (163.1.2.162) by HUB01.ad.oak.ox.ac.uk
 (163.1.154.218) with Microsoft SMTP Server (TLS) id 14.3.382.0; Mon, 8 Oct
 2018 10:10:41 +0100
Received: from mta211a-ord.mtasv.net ([104.245.209.211])	by
 relay14.mail.ox.ac.uk with esmtps (TLS1.2:ECDHE_RSA_AES_256_GCM_SHA384:256)
        (Exim 4.89)	(envelope-from <pm_bounces@pmbounces.feedback.doorbell.io>)	id
 1g9RYm-0004Bi-lh	for ebmdatalab@phc.ox.ac.uk; Mon, 08 Oct 2018 10:10:41 +0100
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; s=20160321233228pm; d=feedback.doorbell.io;
 h=Message-ID:MIME-Version:From:To:Reply-To:Date:Subject:Content-Type:Content-Transfer-Encoding; i=reply-2906565-MZ5OdQapiEHMjs3J6HCYDfCBifaapGjk@feedback.doorbell.io;
 bh=5MoKQuVkkkX3Fob+dXA42xZ+ghE=;
 b=DgrdlcTPmH+ZcsfYkXq0XoNAhpXhhF2BaWAq/3k33uwT6R2rFfTIpoXM1/olGq9LG/QDV9p7nAwy
   qP3LSGiSuvk2LKscXBjGIZktETuc4wpA4DKHFIMPTo4Gqr5Ks5T104oSulMLoIfhlUtNJY3BewHO
   Kpr9gwRQW7Lor7LhDbo=
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; s=pm; d=pm.mtasv.net;
 h=Message-ID:MIME-Version:From:To:Reply-To:Date:Subject:Content-Type:Content-Transfer-Encoding;
 bh=5MoKQuVkkkX3Fob+dXA42xZ+ghE=;
 b=AXu46sAH5x6kumdhwfcFAkC+GbuDcy1dWgtBGh2vTQNQz+Fy/ddHTyq141Lj1Tf7p2dJoMZ+aNOG
   JQXmAdUNlvDZ0xTBEf6aiwJYpxRnnp4xhh29oDl/KNMIUjFp4UC1d7/WdMqHgtmyhtpP87yWZulY
   l3GCVr4IO4RAqjr1kb8=
Received: by mta211a-ord.mtasv.net id hncfh01jk5k3 for
 <ebmdatalab@phc.ox.ac.uk>; Mon, 8 Oct 2018 05:10:38 -0400 (envelope-from
 <pm_bounces@pmbounces.feedback.doorbell.io>)
X-PM-IP: 104.245.209.211
X-IADB-IP: 104.245.209.211
X-IADB-IP-REVERSE: 211.209.245.104
Message-ID: <feedback-2906565@feedback.doorbell.io>
Feedback-ID: s1884775-_:s1884775:a107216:postmark
X-Complaints-To: abuse@postmarkapp.com
X-PM-Message-Id: c9a535fd-4b93-4098-afb5-decdd10049ce
X-PM-RCPT: |bTB8MTA3MjE2fDE4ODQ3NzV8ZWJtZGF0YWxhYkBwaGMub3guYWMudWs=|
From: Tim Jones
        <tim@nhs.net>
To: <ebmdatalab@phc.ox.ac.uk>
Reply-To: Doorbell
        <reply-2906565-MZ5OdQapiEHMjs3J6HCYDfCBifaapGjk-1866800@feedback.doorbell.io>
Date: Mon, 8 Oct 2018 05:10:38 -0400
Subject: Antidepressants Dear Sirs, We are
 going to be doing some...
Content-Type: text/html; charset="UTF-8"
Content-Transfer-Encoding: quoted-printable
X-NTG-DKIM-verify: pass
X-Oxmail-Spam-Status: score=3.6 tests=DEAR_SOMETHING,HTML_IMAGE_ONLY_28,HTML_MESSAGE,MIME_HTML_ONLY
  1.7 DEAR_SOMETHING         BODY: Contains 'Dear (something)'
  0.0 HTML_MESSAGE           BODY: HTML included in message
  0.7 HTML_IMAGE_ONLY_28     BODY: HTML: images with 2400-2800 bytes of words
  1.1 MIME_HTML_ONLY         BODY: Message only has text/html MIME parts
X-Oxmail-Spam-Level: ***
Return-Path: pm_bounces@pmbounces.feedback.doorbell.io
X-OrganizationHeadersPreserved: HUB01.ad.oak.ox.ac.uk
X-MS-Exchange-Organization-ExpirationStartTime: 08 Oct 2018 09:11:09.1219
 (UTC)
X-MS-Exchange-Organization-ExpirationStartTimeReason: Original Submit
X-MS-Exchange-Organization-ExpirationInterval: 2:00:00:00.0000000
X-MS-Exchange-Organization-ExpirationIntervalReason: Original Submit
X-MS-Exchange-Organization-Network-Message-Id: 77252e9f-85ed-4f94-0f4e-08d62cfdfc54
X-EOPAttributedMessage: 0
X-MS-Exchange-Organization-MessageDirectionality: Originating
X-MS-Exchange-Organization-SCL: 1
X-CrossPremisesHeadersPromoted: AM5EUR02FT065.eop-EUR02.prod.protection.outlook.com
X-CrossPremisesHeadersFiltered: AM5EUR02FT065.eop-EUR02.prod.protection.outlook.com
X-Forefront-Antispam-Report:
 CIP:163.1.154.218;IPV:NLI;CTRY:GB;EFV:NLI;SFV:NSPM;SFS:(2980300002)(3190300001)(189003)(199004)(733005)(345774005)(413944005)(966005)(8676002)(23846002)(8746002)(1096003)(8936002)(236005)(356003)(105596002)(606006)(82556004)(246002)(61186003)(5820100001)(18926415007)(43066004)(6306002)(14444005)(62580400003)(23676004)(5660300001)(2351001)(42186006)(156004)(26005)(486006)(126002)(116002)(476003)(2616005)(336012)(50466002)(6986002)(74482002)(6916009)(106466001)(95666005)(201323002);DIR:INB;SFP:;SCL:1;SRVR:CWXP265MB1702;H:smtp.nexus.ox.ac.uk;FPR:;SPF:SoftFail;LANG:en;PTR:hub01.nexus.ox.ac.uk;MX:1;A:1;
X-Microsoft-Exchange-Diagnostics: 1;AM5EUR02FT065;1:IHws/y2PBSjzrvn5bpEgMdqDTWOuoybT5AtDG6yFUIe6Eot4U3uTCCbJ5oYhQzCF7hoWvtAPz3mMH99t/bnLwZlm9i2c65fRWZI6fUgQgjRVu1ZC8Vnezq50x3jHi0bg
X-MS-Exchange-Organization-AuthSource: HUB01.ad.oak.ox.ac.uk
X-MS-Exchange-Organization-AuthAs: Anonymous
X-OriginatorOrg: nexus.ox.ac.uk
X-MS-PublicTrafficType: Email
X-MS-Office365-Filtering-Correlation-Id: 77252e9f-85ed-4f94-0f4e-08d62cfdfc54
X-Microsoft-Antispam:
 BCL:0;PCL:0;RULEID:(7020095)(4652040)(8989299)(4534185)(4627221)(201703031133081)(8559020)(8990200)(5600074)(711020)(2017052603328)(7153060);SRVR:CWXP265MB1702;
X-Microsoft-Exchange-Diagnostics:
 1;CWXP265MB1702;3:DVGMcjPyxdVrtf8EEIq8PYl2VTuf1pcNZ8+g0ZkUROmHtSjloPviuADNCUz0wLyNwCEwVHjv6kr27bAX1GEY5kEGw7STj0E7I6750Zscw0vWi3iyMMNQ9epAIsm9xf9nPIl4G5jKvj1Bihu8G1mM2PwADor8Abot6ZNe6XkGjWqGNBkJxVn1e7MRDPseae2KGaIrfwBcQ3lV6OyHNdoKvA3mG33xFYrv3rDdFkp3VlroR5Yl8ThLNBvPili119vFUbrarFZbsZ76k4VT1+MA3tUqAWz5YRajpqd7Sjco/mJC3XlnhBP6DH/Tvlwnm2z84Gel59ctelTQMk+taszzt7CgLurWWwkAspodpczt9zc=;25:9zUWDY8ZBFU07bv/JHeFEgTL18484mLg0aYnTfvrU5jhg1FmceaZoEWU4CAJ6IqcQZaMfzmf8Jru7ZdDvQgLRHWKqHOOhfAEgQtfYjJHaBFJVz5JO5Lbtf1ZcI3TbAWC51QZUYWkL4q47hSnPUEZHv1ijHbrIz+5wNuMHnCVEtXcFHC+mqgSiFuCx8HEtW01hw/pQIEn5oHiap/WKOJYJHwgLB8Od5+Buk1Hr7hGT8vfXV7npC6EiRmHqc9cf77u3QEEvKKbsfnQruIthw0w3bwLb/3Cx0ckbpTwcvwF+61y3qu6+B8mev7TqnbzjFwWRExXFw/iVNSsz70LAmmrNA==
X-MS-TrafficTypeDiagnostic: CWXP265MB1702:
X-Microsoft-Exchange-Diagnostics:
 1;CWXP265MB1702;31:lf4qimBCLJBrULkjtiaM4BIHZXQKryd0sR7FfC0OkDvg3ACGBcGaIa8ss/aqlt1uC0TjYI5sr6lMv0beFOywUOQt+o38QHfUO76PF08H4k0dFgGRJXaiVwonJdkv9WTem4AqynRVKdI2iDRwTjSTsDOSxyiuEtVVsCI38Sk47QTEGp67yvlGSVJLgwUrqtBY8AfBeJH41p7PJI1abXrfhgu9eQAOjPhuxfZQlM3/l/A=;20:Lmp7tsuSTvRIpKsXNVaytYIQ75K8e+txEM8Jreu940TivE/KGG3lM5VeH/Yjq87XcGSNByMlz0yE7cbntPzbU0HPwhSTnVV3mExrFIxmTgwtakWBaRl+WhvW5CTs4duntSAnb1pmErGLODvs7qRr1T19j401FDl2ymdl1uZi6zBCHl+rpJGQOw92sL4JEPM3T9yf0E5YT7aLCz/gZ8yLnmo4gvZh8XHyKt4N+0BPUDJXLg7iUMlqxpSRZYCbkaPJy56TcUiiI0NBp0I1m9AWUAWAebk781pBYsafji8cquhTeq0PWmz3tUkxFMG+vFlrsx8E8RdL1UfVRz52/ezcyw==
X-Exchange-Antispam-Report-Test: UriScan:(66168760481055)(278428928389397);
X-Exchange-Antispam-Report-CFA-Test:
 BCL:0;PCL:0;RULEID:(2018062399030)(2018011200283)(2401047)(8121501046)(52410047)(2018011210174)(2018011211064)(2018011212028)(2018011213028)(2018011214028)(2018011215028)(2018011216028)(2018011217028)(2018011218028)(2018011219092)(2018011220252)(2018011221063)(2018011222027)(2018011223027)(2018011224027)(2018011225035)(2018011229035)(2018011232269)(2018011233052)(2018021202149)(98810176)(2018021203149)(98815176)(823300264)(823350442)(823411253)(93006095)(93003095)(12181506113)(10201501046)(3002001)(3231355)(901025)(902075)(913088)(7045084)(944500087)(944510158)(944921075)(946801078)(946901078)(9300000249)(9301000214)(52103095)(52102095)(52105095)(52106170)(52408095)(98821027)(98822027)(52401380)(52601095)(52606095)(52602095)(52606095)(52505095)(52406095)(52305095)(52206095)(88862240)(88860193)(88889095)(1610001)(8301001075)(8301003183)(201708071742011)(7699051);SRVR:CWXP265MB1702;BCL:0;PCL:0;RULEID:;SRVR:CWXP265MB1702;
X-Microsoft-Exchange-Diagnostics:
 1;CWXP265MB1702;4:GTvnMLbMSmSa7MaSRh/6e04Bgu0MZM1uG9GuYyO1tYHRwr1DZR5T7YNwmy1KLF2l4UJoHS3awUdm9CZCPyaZmS33DDb8WEKssCHczvSkO9nM0o+b5inPzZHQy5sldH0FCtHQCpg5QpBfV/BEuPpeBwnUVEuiddRCJ9g5QT/dPlt59CzIt5M0SDfj730Fw4XOsCc1/XLRQofM5oYhku+HnQMKCAs6bTMkPDlnKLFhkwSOv4bdVZ5lZRS95tnaYXjeTJT6nFG8es8+PoCGXllgCa32WYJl0qNCkWd8jUVhqISV0WQd/Ve9lltDcsiDqNPvWm3uLfDFy9QDArZT9iYJ3AnVH7DPR+kQvOrYimHaVMI=
X-Microsoft-Exchange-Diagnostics:
 =?utf-8?B?MTtDV1hQMjY1TUIxNzAyOzIzOm5oWVFlOGNLb0wrQzVveE1vNW9hUTlVcFFX?=
 =?utf-8?B?UDQzSGVuTDUvNVg0U20yN25tdStlaE9nVDFjZWRVL05zRjhwZmRqUmVGaWFM?=
 =?utf-8?B?dFdvWFFRd1BFSU1PREZ5azJCanhMZEdXUFIvRWFvQW5GNzVQU0lUcmd6eVpP?=
 =?utf-8?B?dlR4Y2lhYjlYYXFOWnRMb2pta3NWeDAxRU1URTB1MlBpZWo1cndDWHlqNndW?=
 =?utf-8?B?RnNTQzBzSEJWbHYvTmw3dUFEa1Jqa2lVY0xtV0wwdFJEYWpoVno3cGNSblRO?=
 =?utf-8?B?TTJ3UDRjZDRPN0w3WWxFL0RGZVBnNlAvQnFmbU5EdFVCRmdHTTI2Rzh0ZDJx?=
 =?utf-8?B?VUtuMnFBdHRVZWRuWHFoZHBMbjZUVHpxQ09acUJLd2R2bmpHUVNVSWt1NHgx?=
 =?utf-8?B?WVJRaWkvRmw1VExwT21zdEZENmMvalRxL05ibzJLV3NtK2poeWNPcHdBem9X?=
 =?utf-8?B?Y3FoM2pPT1lKN0x0NXVUQXdVTUJxcHdHZVZDTUltbUtSc2lCUDFFTUkrVXlC?=
 =?utf-8?B?NUVkdE1LMFh1TTZXS0pKWWl0YnBKcUhDYnFhTmJTc2luOEUxZjRqSmxnQml4?=
 =?utf-8?B?NG4wYnpwY29GaThmSTJxN2pmZldZcWFBNUpvbTR0Y3VNNTRUU1N6MmRVdEwz?=
 =?utf-8?B?bzU5all1VmFZYXZGSENBS0VIWElNUUZNYkRvcEdIUW9MbFNzaU9JRzNhMkZQ?=
 =?utf-8?B?MjZxanVuN3ZPRjVML05rb0ZESGlYcDh3aWFqaCtpR2FCNElhdWVZRDZWT1lp?=
 =?utf-8?B?V042dGhQSW5RRXlYWnRWWGxCOTZwNU1RbkxmZDZCMlZZYUxQY2k4YVl1ZGk2?=
 =?utf-8?B?YkN2cUlPeUNqQTVKenJueWRZclBkRDRqcFRETm1YRng1NXBhS0NudHNyVWFN?=
 =?utf-8?B?TVZJbktyWGNIaUF5WitUK1lPK0FZTElSK2JpVlMzWXlxbFhvcGdLcGlremh5?=
 =?utf-8?B?N1YzcmV0dEF1eUlqSGRreEJaZ1dqY21mTjdSSmRaQUJFU3hjVEJncjJEa0NV?=
 =?utf-8?B?VmYxSEovY1RVdjlvM2x3TjVDeEE3UkJjUHE4R21tNHRhTXVvdytzL2k3dTl1?=
 =?utf-8?B?RlJvVEpBb2ZxSFJLOE5xUzZqN3FOaVcxK0Jzd1ZuSmJWYkFLeC9sQkpPcUQw?=
 =?utf-8?B?cFYzMFRSMzA3VFpaTExnOHJzOWd4NnA1bnJlZjNZVlRjajY2UkR4UVg2M1ZC?=
 =?utf-8?B?NWFmMGEzcDhkOU5OUFVHZzRVQUdpcU9vMTg0Wk43Z2dQM3hFYU52QmVKVTQv?=
 =?utf-8?B?MXlhWkZUS3FHczZ3M3RlUDlBQlA3ZHlNcFl5NEgyTXRITVZvWmtEMHJudWpT?=
 =?utf-8?B?Q21MTG9KQVRJYjRBYnpBZll0TE9uQWcrRWIreVhLWVdUZnFjUmtPbnV1U2x1?=
 =?utf-8?B?RkhiUG5wVlFDN3pNODJSVTZQcFdEcExDbUNtN3RuWWNmMC9IbGxNbjVHMzVk?=
 =?utf-8?Q?RNAofM=3D?=
X-Microsoft-Antispam-Message-Info:
 bRyUe+RElSR3erjjl8r5Dl2GtPIs4cYPww9KFNX7P/HhatjhhMrL0DTVn0+6mGPYl5ehNiFcuGx5zsMoRT8xqo7T3S2wxDx3Cv4gruXHb5ktobNvIsNZL4rlifei1gdUSsvsf9CzGk4B/kl0CnZuJtHqzQZ5nZgdpOyDPL9RIBcNnVJUt1g0QRvhKKmUajsQv3LgY6X5OEDvpczO0J6+pxvgNM169z/WL9wr4xN9fNZtL+ZotEqCFc5lfMogI7aJb+mR8IlLUT95xOsxDWOCRncDveqwGU+5AE2DeU3SFmq93diBJ0eGl3PiVO7U+9IX3J4dgmDPSUhQ/rrHGmwSer3JemfahVmvFkW4zcfuTSrgPS0mfnJPIUWq1Hg9tbIIahdY3AKxulYhK05LklsjQvs7AkeBZtXIHUsgtWuiaeWpwWTi/4ltF0deNrLYnrUnXNGMpqvhj7dsDoDGC5BUVcFk+hDv5Q1ZSqW07YxDV5Gje/cbfLo3SG0z1UE1d3aI2Dr7MMREYBsSCp5jYfZ3SsD3RBq7Opqav7MLfmyyAjWxVF/GHGGfMeKij6fF4amdaFSNZB5tO360te8kHV/qPb6Z9Apy1H/KFirGPR6Sbq/5b99g7VUHcfKZWiIV939GzQvLNzgNledgsAX/CLiKWJ/U1IlWtvpCfzWNr5H1Lt7uuOl467ibdYe50tZlzFk2GZvf/4x3E0J0mPJaLIdMh6HGWd79S3/Yl4Ofezi48PE8smsFTRdVQ4Uo8k/8fCQjI/hOSuiYLr5tOA7YC11ODg==
X-Microsoft-Exchange-Diagnostics:
 1;CWXP265MB1702;6:wmViPqJ5pzQNxo/wviVcpj1IXNRBjdBeStFZh5WiP+BXBQ/top8A3bbn342rNYrI+HU9GQMJ3IkB4YsFNJOS/WRULG2lw4I8A01yJ10b7S3d9YoIc9Pc3p0WcMNb2NZsC/o3DgXnTAEBJAW+O7a1aLRUjziC032XCcXRmepxnQ87z1ENxcMiDW8Bjb2WEo3Q/dle1p1fx2T1YcW2JiucUmEneCsbJ83NVEdNn8CvCfViJ+xBnvdBGiT36Zyf6+w1iVh+ir/PE+EiACxLJFbxCjO2t2UAHQtyH29qkQ+wQXl0xHHPTKVzID+W0eNwqn69Apn7T8wRr5kpu4yPUIchxGaw3iSlAfqsZuP67NW+QXLTuBYbGBBKIKwpoGap/HZsQ7p2LDJwqYSPNa4bA4DqI9fWoqC0biOWg5DYDqDZqCz82icwo0QogUab/Bn3QqENDleDJyu162zvjJI2XRSzCg==;5:7F+TKynZf9UqeEDb8P8C1lOmN1omXsHrdf2eQEStpKhrmJOdytrFtehgvibK9Lvc3ulDjkrlkyr1050Mhp82JbXlNRYysWGLUX229jCmH4HsAjMQYEMC1HJXOREwOzeqfvInPlI7+r+y/g/4ZiZGCRe1xfE6rQhe4MpNB+vhn6U=;7:+LEiNLDJ4dQaH8aEvNbzKoZ5GVYmFFeSedTu6kw9RWC9by0MFun/PW5DF6DGjCTvErhuIk0xbqopiGoAtDlR0RKZst04w62Eg0NU2UhJmWPCge1y8GBVOOgw5nFPok3JWfzw+/3gqXwBI+xJArop1z6mt4KN+FTZs3zF5YUQz+/WWcry9DZakQPQaZ+9wDxpnr7/SCkNByAidr29iEMHt4KfK+V9V4OXeMNuFop7V0Qz6O/QWdWjOEFdUGi1v0VX
SpamDiagnosticOutput: 1:99
SpamDiagnosticMetadata: NSPM
X-MS-Exchange-CrossTenant-OriginalArrivalTime: 08 Oct 2018 09:11:08.8875
 (UTC)
X-MS-Exchange-CrossTenant-Network-Message-Id: 77252e9f-85ed-4f94-0f4e-08d62cfdfc54
X-MS-Exchange-CrossTenant-Id: cc95de1b-97f5-4f93-b4ba-fe68b852cf91
X-MS-Exchange-CrossTenant-OriginalAttributedTenantConnectingIp: TenantId=cc95de1b-97f5-4f93-b4ba-fe68b852cf91;Ip=[163.1.154.218];Helo=[smtp.nexus.ox.ac.uk]
X-MS-Exchange-CrossTenant-FromEntityHeader: HybridOnPrem
X-MS-Exchange-Transport-CrossTenantHeadersStamped: CWXP265MB1702
X-MS-Exchange-Transport-EndToEndLatency: 00:00:02.9424701
X-MS-Exchange-Processed-By-BccFoldering: 15.20.1207.000
X-Microsoft-Exchange-Diagnostics:
        1;CWLP265MB1699;27:AAVZpB1VBnRjQeUX/YtE+MEw3gQ/EHcK6SQqmovXLDxvTKLMZ+8yiMp3hoJdc03lEqbkONpgzV3nIyqxvXagr2xZ8Y8u8UjAmZ2bT/IEe17NWml+Y/NSn7NLdhQIzptAHfaa12xbb4wufGQLlKM2MSUvtqMQ9jRfvk33xOga6HwULi5Zt2CO1FHiJW6fOBcivoz0AupD30M2ABoM46ag078U2ZarNsLKtQVN4rXE1K4BhH7DKuUThlWfk7x0PuZEMvflz+U2dI0ol/1LI/Q6lTF5QBZ++30Q6Nfrmky/5V9Fh6CZ3Ft1OImEptilGxXX9tZjp5matDbGSudT6DGDUGnbImNrt0IzekCgvvRp102BR2rGeuMSeMQm/6d6ALnN8VCp4nYkODJrJ9YF/c/HAg==
X-Microsoft-Antispam-Mailbox-Delivery:
        ucf:0;jmr:0;ex:0;auth:0;dest:I;ENG:(20160514016)(750119)(520011016)(944506303)(944626516);
X-Microsoft-Antispam-Message-Info:
        L7aYhip4lURSpOCSbubxHZ2pQg6VVziT4VB0xK6AcRJswnFXY/7Th8euUJ6j4YwjysmntaB7o2nEgoX7kukeUzJvFyQuMKRuJUjCG44JMjXr8PLbUIIwMM+u91Aupuu3mLFpDvQv+YRISguwEpSE5YWL4+7H+HYejCWl/oVsFLm0JtOwrDHei1o48w4C8lW/vQhR8rMQvnPCrBkCvgzRLHiCVozuhCrDcDTrfEO809icb7KO5HKdCyfPr/SltAm2sp8TmLZQ5DlqlOH+72T8oPkNkeU1othvSjFD7KLCnoGu8WKZYBs6dQYz9KB6PmHTcqil7fE63SUSD+ax0kjjQiaRaQnx+0ot6k+kZIK2bLUB5te7mGtksb8SAU+9NJ2Gmo6XcAzBVRhyAU4BrraHhoedS5wKAM0CaU/FbN6n47kEFnV4iCrVGL2AmrL3OpJA+3w1DLpl/ME+riJrWutijcMnJvrvRvASkbo+ULc4mxyj+yWnT3jAiFpUCLTQnB2KEekPageYRxAYVULZWCdUoTf2QZreapnGE5ECE8u7sOTwYHBw1ByBmaQ2LEkAouhLNBxDxs710mK3XpyjvhrM6+eH4ZqZJwP/oU/8Je7CwV448VKbokgkBeWFRcz31VR0A4tfzeZYNnHm6h6+2OxLlg2Dvf7dVKG6Khbwr5cU8/KcxtxE4TTvSKq8YW32nOqvlIFpXseFgNQijUq74Ovr2JNkcYzGXePnWhVp2KOXtlQJsxHfeSlWFPbCfgeZudOiqEJ/XlY5Qz0YyuGDN2NhvdHUwSNmkWUOOxOwGhRzUKuthmr8zwmFp5KzXLJOvPqZOLHggna2tLipCSsOydaDLQ==
MIME-Version: 1.0

<!DOCTYPE html><html lang=3D"en-US"><head>
<meta http-equiv=3D"Content-Type" content=3D"text/html; charset=3Dutf-8">
    </head>
    <body>
                <h3>New feedback from tim@nhs.net</h3>
       =20
        <div>
            Antidepressants<br>
<br>
Dear Sirs,<br>
<br>
We are going to be doing some work in Southampton City around antidepressan=
ts , especially reviewing patients who have been on ADs for four years and =
more.<br>
<br>
I just wondered if you could send me for each practice the numbers/costs of=
 patients who have been on ADs for 4 years and more , prescribed the follow=
ing in BNF paragraphs:<br>
<br>
4.3.1 TCAs and related ADs 4.3.2 MOAIs 4.3.3 SSRIs 4.3.4 Other ADs drugs<br=
>
<br>
This is so I can have some numbers of patients that needs to be reviewed an=
d also costings to the practice.<br>
It would be useful to have some figures for the whole CCG as a whole as wel=
l.<br>
<br>
Regards Tim Jones<br>
<br>
Tim Jones<br>
Locality Pharmacist<br>
Medicines Management Team<br>
<br>
Manchester City Clinical Commissioning Group<br>
First Floor, Folly Road<br>
Badbrook<br>
String<br>
GL5 6TT<br>
<br>
Tel: 022 1234 123456<br>
Work Mob: 07777 887887<br>
Usual days of work: Tuesday, Wednesdays, Thursday and Fridays<br>
<br>
<br>
<br>
***************************************************************************=
*****************************************<br>
<br>
This message may contain confidential information. If you are not the inten=
ded recipient please inform the sender that you have received the message i=
n error before deleting it.<br>
Please do not disclose, copy or distribute information in this e-mail or ta=
ke any action in relation to its contents. To do so is strictly prohibited =
and may be unlawful. Thank you for your co-operation.<br>
<br>
NHSmail is the secure email and directory service available for all NHS sta=
ff in England and Scotland. NHSmail is approved for exchanging patient data=
 and other sensitive information with NHSmail and other accredited email se=
rvices.<br>
<br>
For more information and to find out how you can switch, https://portal.nhs=
.net/help/joiningnhsmail<br>
<br>

        </div>

       =20
                <p><small>You can reply to this email, or visit <a href=3D"=
https://doorbell.io/applications/4272/feedback/2906565">https://doorbell.io=
/applications/4272/feedback/2906565</a></small></p>
       =20
       =20
                    <img src=3D"https://doorbell.io/email-notifications/ope=
n/1866800/5568ecc2-4398-4549-8ad8-55460f1121a5" width=3D"1" height=3D"1">
            </body>
</html>
