Received: from CWLP265MB1698.GBRP265.PROD.OUTLOOK.COM (2603:10a6:401:25::30)
 by CWXP265MB1702.GBRP265.PROD.OUTLOOK.COM with HTTPS via
 CWLP265CA0258.GBRP265.PROD.OUTLOOK.COM; Wed, 26 Sep 2018 20:04:11 +0000
Received: from CWLP265CA0014.GBRP265.PROD.OUTLOOK.COM (2603:10a6:401:10::26)
 by CWLP265MB1698.GBRP265.PROD.OUTLOOK.COM (2603:10a6:401:35::16) with
 Microsoft SMTP Server (version=TLS1_2,
 cipher=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384) id 15.20.1164.22; Wed, 26 Sep
 2018 20:04:09 +0000
Received: from HE1EUR02FT037.eop-EUR02.prod.protection.outlook.com
 (2a01:111:f400:7e05::205) by CWLP265CA0014.outlook.office365.com
 (2603:10a6:401:10::26) with Microsoft SMTP Server (version=TLS1_2,
 cipher=TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384) id 15.20.1164.22 via Frontend
 Transport; Wed, 26 Sep 2018 20:04:09 +0000
Authentication-Results: spf=softfail (sender IP is 163.1.154.216)
 smtp.mailfrom=pmbounces.feedback.doorbell.io;
 UniOxfordNexus.mail.onmicrosoft.com; dkim=fail (signature did not verify)
 header.d=pm.mtasv.net;UniOxfordNexus.mail.onmicrosoft.com; dmarc=fail
 action=none header.from=feedback.doorbell.io;
Received-SPF: SoftFail (protection.outlook.com: domain of transitioning
 pmbounces.feedback.doorbell.io discourages use of 163.1.154.216 as permitted
 sender)
Received: from smtp.nexus.ox.ac.uk (163.1.154.216) by
 HE1EUR02FT037.mail.protection.outlook.com (10.152.10.205) with Microsoft SMTP
 Server (version=TLS1_0, cipher=TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA_P384) id
 15.20.1185.13 via Frontend Transport; Wed, 26 Sep 2018 20:04:09 +0000
Received: from relay11.mail.ox.ac.uk (129.67.1.162) by HUB03.ad.oak.ox.ac.uk
 (163.1.154.216) with Microsoft SMTP Server (TLS) id 14.3.382.0; Wed, 26 Sep
 2018 21:03:44 +0100
Received: from mta216a-ord.mtasv.net ([104.245.209.216])	by
 relay11.mail.ox.ac.uk with esmtps (TLS1.2:ECDHE_RSA_AES_256_GCM_SHA384:256)
        (Exim 4.89)	(envelope-from <pm_bounces@pmbounces.feedback.doorbell.io>)	id
 1g5G29-0001sN-c1	for ebmdatalab@phc.ox.ac.uk; Wed, 26 Sep 2018 21:03:44 +0100
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; s=pm; d=pm.mtasv.net;
 h=Message-ID:References:In-Reply-To:MIME-Version:From:To:Reply-To:Date:Subject:Content-Type;
 bh=UBx29sKs8JCjNxBVpSMvvJU7hSU=;
 b=zB9weZGSs4wZuKU8JN7BShQE25DbGuWdosJ/csvFbu+QDIzVvORVXupGDXKOj05PDhKIR7stDfBT
   WISFFk7pBMyaPeKtOQ1E8M3TSXMmr4mOKN3RIWKgY3wZ1fUHxV8iAF33ueYs4Ln4AkxyijN02hdi
   hT+kDZRDyXAfrhWZL24=
Received: by mta216a-ord.mtasv.net id hlfj1q1jk5kk for
 <ebmdatalab@phc.ox.ac.uk>; Wed, 26 Sep 2018 16:03:40 -0400 (envelope-from
 <pm_bounces@pmbounces.feedback.doorbell.io>)
X-PM-IP: 104.245.209.216
X-IADB-IP: 104.245.209.216
X-IADB-IP-REVERSE: 216.209.245.104
Message-ID: <reply-321559@feedback.doorbell.io>
References: <feedback-2880002@feedback.doorbell.io>
 <reply-320753@feedback.doorbell.io>
In-Reply-To: <feedback-2880002@feedback.doorbell.io>
Feedback-ID: s1884775-_:s1884775:a107216:postmark
X-Complaints-To: abuse@postmarkapp.com
X-PM-Message-Id: 3ae59f49-9379-4a9e-8aad-1eb710da3dec
X-PM-RCPT: |bTB8MTA3MjE2fDE4ODQ3NzV8ZWJtZGF0YWxhYkBwaGMub3guYWMudWs=|
From: Seb Bacon <seb.bacon@gmail.com>
To: <ebmdatalab@phc.ox.ac.uk>
Reply-To: EBM DataLab
        <reply-2880002-s869PFqS2FhSyDwUjg6ASbq5BomHGz0D-1841992@feedback.doorbell.io>
Date: Wed, 26 Sep 2018 16:03:40 -0400
Subject: Re: New feedback on EBM DataLab - Dear OpenP, Can I possibly obtain
 prescriptions numbers dispensed by...
Content-Type: multipart/mixed;
        boundary="--boundary_7370456_bc379558-a15b-459e-90d6-002a27f16110"
X-NTG-DKIM-verify: pass
X-Oxmail-Spam-Status: score=1.1 tests=HTML_IMAGE_ONLY_32,HTML_MESSAGE,MIME_HTML_ONLY
  1.1 MIME_HTML_ONLY         BODY: Message only has text/html MIME parts
  0.0 HTML_IMAGE_ONLY_32     BODY: HTML: images with 2800-3200 bytes of words
  0.0 HTML_MESSAGE           BODY: HTML included in message
X-Oxmail-Spam-Level: *
Return-Path: pm_bounces@pmbounces.feedback.doorbell.io
X-OrganizationHeadersPreserved: HUB03.ad.oak.ox.ac.uk
X-MS-Exchange-Organization-ExpirationStartTime: 26 Sep 2018 20:04:09.3263
 (UTC)
X-MS-Exchange-Organization-ExpirationStartTimeReason: Original Submit
X-MS-Exchange-Organization-ExpirationInterval: 2:00:00:00.0000000
X-MS-Exchange-Organization-ExpirationIntervalReason: Original Submit
X-MS-Exchange-Organization-Network-Message-Id: 8e14a9ce-2f31-440d-d014-08d623eb3897
X-EOPAttributedMessage: 0
X-MS-Exchange-Organization-MessageDirectionality: Originating
X-CrossPremisesHeadersPromoted: HE1EUR02FT037.eop-EUR02.prod.protection.outlook.com
X-CrossPremisesHeadersFiltered: HE1EUR02FT037.eop-EUR02.prod.protection.outlook.com
X-Forefront-Antispam-Report:
 CIP:163.1.154.216;IPV:NLI;CTRY:GB;EFV:NLI;SFV:NSPM;SFS:(2980300002)(3190300001)(189003)(199004)(336012)(733005)(486006)(95666005)(6986002)(575784001)(6306002)(5660300001)(122386005)(43066004)(229853002)(6916009)(3380100001)(2476003)(568964002)(105596002)(356003)(21490400003)(33964004)(34290500001)(2351001)(71190400001)(106466001)(606006)(446003)(76176011)(11346002)(84326002)(966005)(8936002)(62580400003)(4610100001)(74482002)(6246003)(82556004)(26005)(116002)(1096003)(236005)(126002)(413944005)(16586007)(53376002)(8676002)(476003)(156004)(5024004)(18926415007)(2616005)(42186006)(246002)(4810100001);DIR:INB;SFP:;SCL:1;SRVR:CWLP265MB1698;H:smtp.nexus.ox.ac.uk;FPR:;SPF:SoftFail;LANG:en;PTR:hub03.nexus.ox.ac.uk;MX:1;A:1;
X-Microsoft-Exchange-Diagnostics: 1;HE1EUR02FT037;1:RFP6LSorSC+ydCBwuP3d0tqFE+ZeDMB6XB1kB7AktcX+MrzuIRnH9gqDWj8R+wEdXSkdM2nMaK46QCg3/tSB2t1LJmQ8m8iabMGHR4L4Br4H+RRwNEZ5CWDX2bGa5ks+
X-MS-Exchange-Organization-AuthSource: HUB03.ad.oak.ox.ac.uk
X-MS-Exchange-Organization-AuthAs: Anonymous
X-OriginatorOrg: nexus.ox.ac.uk
X-MS-PublicTrafficType: Email
X-MS-Office365-Filtering-Correlation-Id: 8e14a9ce-2f31-440d-d014-08d623eb3897
X-Microsoft-Antispam:
 BCL:0;PCL:0;RULEID:(7020095)(4652040)(8989299)(5600074)(711020)(2017052603328)(7153060)(49563074);SRVR:CWLP265MB1698;
X-Microsoft-Exchange-Diagnostics:
 1;CWLP265MB1698;3:K8Nbb5K3RV4T4MQ6Fhev/4Oi02wxaMvPxud/Nmi/lBEAj2qLgaz+/AwO0oj5KSkXrQRx5JuIVTVqiEFNEdFL8fFWAJrN47D6Wx/Ti+8D025Gsa+sudCXvpJqqiygg0Haq31gKrlK2VvgrDeoCSQDfzywfIc/IpshiWukIJI5fB9iD9FFdlTTorDyjxxpPFb2aCgmzEnti+iUTjdBb/ntmI0vYLns1jg6LrYvvpKFtNEicshLSWYuH9f/W6hq5WZE1k3KjIvv033bxvtUmBa1fj0zE8o5hCQyf+2ZzdCEgBdO24qOmTUoX/P+/ERJuif1OyvP0jwvUFGzHdfFrCpWCRJxmlecwz2NrgEG+ep2N2g=;25:V2aVF5573Im/J2eYQQXcF3xKKN30QBKS0PEmVvT5yGEbpNwYXTecp3mb8zkay111A0HyfNQFI7fHUiQKVbf2GSPnbr1isZcFlX97ThXTcl2gSdDHvgwCcr6sXWp6+NmqH0f+HAJcNnNw9HozNNWyXu+3ZOUwQRnrll7PUeua8IQM0shhSFpyJqYF6ZyEHFzz2X9YwNIQoQ53AsflMU+qMJvkJkSGX/toN9kHqN+E7faIwOoysyJ49awDTut6vVwpIwBkHHLde+U9pVghRP02FNbLx88cT9ddjUZYNiOz/cBNn4e+cmXdggYMNMf/+Fey8xHuu9nSmXNsl578XdMlvg==
X-MS-TrafficTypeDiagnostic: CWLP265MB1698:
X-Microsoft-Exchange-Diagnostics:
 1;CWLP265MB1698;31:GXmdlqIfTJdTEWfO/DMqXiPs5K6ZJnfJ2ca8kjn4chWpHAYWl8jr204alWkmM2ZiNqpRLLbk8pjrig/zxJmV3vjs0lXgcATorqRTQLLQTzm5q6LIO+67z+Sa8SefJWIi5qcXX+ZlX3E/hTfmBuxqNyXSPZnFY3hzXjvKo+UNLFTB/YwRU/Xsd+kCOCep6WyZxnxe9Oqw7DoGS28x7nuAiflKEoielWi6V3SmLHrPGVc=;20:3zTTYPgcmdBo0cQY2fCBwAZQ6SH5hE6Od/AHUy2bEfhfDndBIa3LAvMnijqLu9thAV4twwylWsl6YluQsFN0FDmwMW+k2d/xFnm0XOCkLYwWG8XWv7/7VryssU/+AGgbFLK2p1B0pl3rmZnu7hqLExniLeIRLsM+mmCRzF5bXw6FMMQz9E8Z1e3/duZFn+FcUTod/rsS592fU/RkZgjf+lH9x+JI5xewQ56yVYTcVosXxpg1ZiwDItiIKLoogxoPFo5mWdfRKoLfEoD6SeOS27WPXfORmF3S+vCLd3SW5P9kjmy4idwCtfPUkx6JgeIsIDyArPckHc3sz/g9sNCl1q9oZdcMVjVbbYSKJBFSLTw/6LkJfQ/j58+ZMeutVGgAeJQTyalonOZLbUNecXTlls7kqz2KVnXqugsq/iLkI12YT5N7HlsMSMbdqeh3ioWTp6pGk1ft98StZdQ0hUyVYqjEtnaWSFpmotC1cD+rg0MVCNUVnkNrQCNsCChDCZm4
X-Exchange-Antispam-Report-Test: UriScan:(278428928389397)(85827821059158);
X-Exchange-Antispam-Report-CFA-Test:
 BCL:0;PCL:0;RULEID:(102415395)(2018062399030)(2018011200283)(2401047)(8121501046)(52410047)(2018011210174)(2018011211064)(2018011212028)(2018011213028)(2018011214028)(2018011215028)(2018011216028)(2018011217028)(2018011218028)(2018011219092)(2018011220252)(2018011221063)(2018011222027)(2018011223027)(2018011224027)(2018011225035)(2018011229035)(2018011232269)(2018011233052)(2018021202149)(98810176)(2018021203149)(98815176)(823300264)(823350442)(823411253)(3231355)(901025)(902075)(913088)(7045084)(944500087)(944510158)(944921075)(946801078)(946901078)(9300000166)(9301000214)(52103095)(52104123)(52105095)(52106170)(52408095)(98821027)(98822027)(52401380)(52601095)(52606095)(52603095)(52606095)(52602095)(52505095)(52406095)(52305095)(52206095)(88862240)(88860193)(93006095)(93003095)(3002001)(12181506113)(10201501046)(1610001)(8301001075)(8301003183)(201708071742011)(7699051);SRVR:CWLP265MB1698;BCL:0;PCL:0;RULEID:;SRVR:CWLP265MB1698;
X-Microsoft-Exchange-Diagnostics:
 1;CWLP265MB1698;4:ZDiH2ngNQArbXmbWaRC87S90PLsw2X/rj+gvw1aEh7BZuCzGOm30PoQE3tlkPhnpSuam1TMVFLj7LAczqq1nJS31fmRLacoSExMBunzX4UDvNKE86Hxjnh8cNEtxVt2l5txZeB7QQK/Y8iHChYHNFG+HaBpcefwc6lO4Wx6FLI6WmOximb9fyG6TSsxWceLMr3kBMcIV8nCRGa9wllEpnJXeW0Pm2OhnVRYI3cQ86/g0NUgw1n5C+Jvvi/JQ/qh3MAWnhh9Q9QFZOHZ8MSS3LBOZ0DWLSamzWkjiG1LIS0rzJjFiynPzNkbfdVsNu8uBeD0ThsXetvpJUdGyMx9BLi55RkCtWV7Zxrdpi7QQFcQ=
X-MS-Exchange-Organization-SCL: 1
X-Microsoft-Exchange-Diagnostics:
 =?us-ascii?Q?1;CWLP265MB1698;23:W8pq6pPLF/KISUF5RJvq2W1rsA3V6q6xni8V0RrUu?=
 =?us-ascii?Q?aeEaTr1TWztNdSsX7qPw470pv6ngktPEvdWjwITh/kxVvTfpHPCsJdQ8qK/E?=
 =?us-ascii?Q?/oRa9svH+JNpe8tjO/4IXzhghllmwCTRvPGq7xzJgelLoQ4CT2Z1ISgqOd9C?=
 =?us-ascii?Q?x41EI5XyQTA/52S4GMHX0hWHcQE84RyRESLXGAW7TQvoBBVNmYLjz3xC/Knp?=
 =?us-ascii?Q?E7pul/TDP5JG5Mq8rgJXEtSCIfYKkfeZRRiEK3fVd/Q3icevnL273Oe1YTJ9?=
 =?us-ascii?Q?saoMNv6gp+ioNp/cb5VfXMDcuqnYn4LqnYESqLf3bvymb96mf2z5OApP4ekg?=
 =?us-ascii?Q?F4QC2Xzd3cJf/XKqtykBRutNMpiYlikx1emHqtX+IghDX8UV8Wfb+KrQ0Rhb?=
 =?us-ascii?Q?HHPGBinu7bZsyDnL04ezB2VF5f5kn5NwTsNw9Uzp7dPXtswlcDogrxl4g4Dm?=
 =?us-ascii?Q?hdoT1rmUUSGyfHZBU2NsHpaoV/uwKknbodQiKuNjPVCyJmRN/NguHtKJ19dO?=
 =?us-ascii?Q?sdyKksR6wi0j/3etBkyH9Nno6CWb5Hk7QCN2wpw1hYxIFojLzpOEJyiu4RTk?=
 =?us-ascii?Q?faSeqoayl66XkjiABWFqsf5rmhKVVe17AValJc69wos7SRqGW7OAPYqe8E/B?=
 =?us-ascii?Q?x07s8jBU9hFeoYBQLsMFzbMmuL49++gHL/shHv6ih5WzkgnOWGOEUnWPEmkk?=
 =?us-ascii?Q?1FXtcf8PiZe2uhj10+ui6tktqb7dnOu+BLMb1a319KRUQU8xcUIPEg1sVh+E?=
 =?us-ascii?Q?RVt1IYU/WYFgsXIj05pnImyHOQyFhV4ZNmGMQKtC6eCI+4HckYoGmdfaYZGG?=
 =?us-ascii?Q?TWHnLSj7B8nTZIpBQ9FXk/6Cergg92Qb02jiHnLbSN3ZQFu1kvA9N7Pv4FDI?=
 =?us-ascii?Q?mIIjXPMf8HZHwylFDRNeksjOC3lMvuprJZ2wGDpRQCbIGEOf21KTEVabiTbm?=
 =?us-ascii?Q?2qmhZLFwVYV2hY6BZrYsuwB2EQ5LC5YeulNPOdMpuq4xo4X6yP6FjcGwHxY1?=
 =?us-ascii?Q?CJGYEVu+5yjdY4KZmpsHOQMpUw29/u7vs+kqe5MweDb/l2xWX+0HEHxnnX+Q?=
 =?us-ascii?Q?udq7AwtE5LyeSciH5t2nrUSotMk0cQXAq+5PpSSaDhddDK7WWS6LK2iNagAm?=
 =?us-ascii?Q?/HJUQIO7O2pSAKDx8iQl/iteS8Hcz9a44gz7kRJfgUdp1Bd4112WF5839c9E?=
 =?us-ascii?Q?j4QZ59k1ciAJwVxE38ArWmpzTE6JIgxjEtC4JGHcB9ZFtVu4C0cLeX14lknq?=
 =?us-ascii?Q?KhtxFW9BY1KWG60TTJmsEnjW++gikRu+ulzsyRfUd73V0SMv5NBIlQOo6jin?=
 =?us-ascii?B?QT09?=
X-Microsoft-Antispam-Message-Info:
 UiLUnfvt+24Gt94nYqxe3PiRzCZzIJehvZBwv/mbhaVUJzXukBVcblwjR9IaLyS3SedLl07379GdCUXIerRjj7p4hOIGTeVq+Yzun0YRBe9MnoPBBYTMd4UvUdj7EqzCLWVInEVNEoCpgxhfStZJQiFVcA/ZcuC1YuEu9KIm/zwvZ0Buz8JkjJkfu8ZzQ2l7lnHglhiewfW4e62DWjZWyMWmOMHrTOFt0lZw7SK77EY7tduA3RNbbNVb26DblVjkI7iIte4hT55dmx9Qo5+tKBsHnPBlQTbZbcfCYkzOm40kj9vcgnudFyUQfQ4P+yt1yBfxvbHhcUQAF0yFDPh3ktKs9KDfwpKsb0NpAcOg0NMpVNvk23XJMldkJfrump8Ysq1jF5GHrTZRnwdHoIxCxqs6YKMz+mH0ieX5s3ZMaeWC6k8geoX3O/q+ugzxr4p7AMGFNFqEMRjLVXYn+z4h0IVHCn8xU6E/UwmJfBSSFQifyd/DJQ+yQCjyfZCBDtTUm3O2HgLuwNaKsiczjdCQfATiNXxdo3Y2UNclRIQFHpgyZ2GbYC43NPEWbYEawIPneiIPMK4R2gXrX/PNcFe2PYvw7hPNhjmk8r6FWvjej6RhdBKVAcK3atxCF1nrIB4xJgNOXbgyiZTjCNIZNLBcwW7KO5Kabw/y1eeJcQuKxFxYeHj53xcWheSQlMQDqdY19PPyO5mI9AqFhSeCo0Db3VKIotuilyZnGpy5Nq9VFIA=
X-Microsoft-Exchange-Diagnostics:
 1;CWLP265MB1698;6:2a0c90HA+ZmwBi+cX4O+kq/qaLS3tdH8qeLnMmz8AXbMwWWIGeh2nvo6x4GL8fYZKrTMGSw3N1Ek/JZITjTxr8mCJbiIXdHX3Dxk2z8RHPwkCik//LQ5E0UB97zmOSIpzUty6li+SDNJaklO4mQ6ywrWc0BTzfupmKne0eLGTs7XQIAA5MWGwGDzVUxwoUYPq/M9WtjeESxbHqdG326+tmJHjsMEQR48tHd7J3RazSeFJbnHXKnKLJ0Xh6kmqx2ftaxOnqWxM7VemkjS67UXXBwUJwRoCBaO4V/UCsIuERYwkmtKJJKH1YaLhtlea4I1FXssJ6xJSudS5QbynnaNK0vP34UfPcLD5cG5DR6qaioxsPX45eF1fctHmFXfYnYeMpD1/rsi0mzVALKCcGyesIGOtBijpsKvmbh1ukmJlR9QbBW5NDjAiwxTbnULOnJSnqliP3zxuLSP82nFU3n69w==;5:Cvmyyy47iF9fbA5npl5+2veip0+SlfA6u4zdf5kw1RhsFtPwn4mm1vKCb62cHnKEQ/COAzRNNWhJqHl+HRsSoyR647hGxCWxugeDAwQ3/xIwwkVEK/rQEiEGvH3+3K4TEkUYlinNiowG6StJr7t0l7AuFGXuIJfkEVPH7yn5UYE=;7:OcY61UDJV8XuxszhXuRi0Hk7OcTHAmZQiB3xIE1aVAekLgltA6DTGY8fn2plgtpjM4Co1SaYitTQ/wZTyJtieeYv41H3qKv4uMMVvtqVoSbJ3sd4H1SOj3DJg8ghXReryoKX18HPemRtwodQvvGmWEeNyyZIjD+HcSDoFOg9Wlz8ifBJSvfC0uN2aJGoEH8EJeKYqrQF+TpgseN5tKHzRrSZ37j0k5W7bMLmoqMpFaLKbHXTHff5CzvGwyFkutzF
SpamDiagnosticOutput: 1:99
SpamDiagnosticMetadata: NSPM
X-MS-Exchange-CrossTenant-OriginalArrivalTime: 26 Sep 2018 20:04:09.0451
 (UTC)
X-MS-Exchange-CrossTenant-Network-Message-Id: 8e14a9ce-2f31-440d-d014-08d623eb3897
X-MS-Exchange-CrossTenant-Id: cc95de1b-97f5-4f93-b4ba-fe68b852cf91
X-MS-Exchange-CrossTenant-OriginalAttributedTenantConnectingIp: TenantId=cc95de1b-97f5-4f93-b4ba-fe68b852cf91;Ip=[163.1.154.216];Helo=[smtp.nexus.ox.ac.uk]
X-MS-Exchange-CrossTenant-FromEntityHeader: HybridOnPrem
X-MS-Exchange-Transport-CrossTenantHeadersStamped: CWLP265MB1698
X-MS-Exchange-Transport-EndToEndLatency: 00:00:02.6564838
X-MS-Exchange-Processed-By-BccFoldering: 15.20.1164.016
X-Microsoft-Exchange-Diagnostics:
        1;CWXP265MB1702;27:yYG1/mA2Mmr4qaVVfQxqqooRfwbWb+QpouFAgi8GwDUon7asxLle8YsHWP+r09m7r7J5Ivy3p5HN0h1MEKx7ZOLHxkiS+PijBCEuyhA3NJYSeppdHguvUBTOmOyiThcLmMImyepblWTpwEHs+LoBJSdIlBtGy5PAtDYd1xJQAQid9GMmLqMvSSWEpkTUSvHnbNjdIKEFw9YLoReMf5NhzfXUFC6t1OEsk8vrUnDsWzDAYdk3EhiGRuNCQ4yVSIt71WtgDJfNbQQWkOTd9WQHV7X8qLYyESmIXXL8dAx4yD8H/uMyEWhvECSpfSSSb8k3k7CpfiN4G+ynQJBmxbKtUmEJOrlpJshIwVVC3JDJe/c3X0Pw1wUMcYA3xNP3NJr0LZSxSy4idHku4ZxFYK9nug==
X-Microsoft-Antispam-Mailbox-Delivery:
        ucf:0;jmr:0;ex:0;auth:0;dest:I;ENG:(20160514016)(750119)(520011016)(944506303)(944626516);
X-Microsoft-Antispam-Message-Info:
        DpFnbMwSHCNNNl7kvmWEeymw+wyoJuGhhgV0D/h7yWgSw30IrqwQPp+WBkgpZJEPaTV00ClhMeFjy+KWmDwZtVPBaj/vUyb1yTEy8KbUz73LSy2cp/vlLRQO9Uw15klo1U6jCqQ5EZf4ZSlzYy4vhhAS+lyPaXcXUS3+Wb9YmOd3VbRvMFNnQmSqEoEsCs39CFXrltT7larL88wjYDIxkHt/97vN5SoE8w9eouiUNEtHjdzRW5GWqNK38oTSgZE2zcC5j502GUJSDteT+Kswao9CK+9Bf9wyK3UFelCldEdGVgHlBJcYEXF6kILpXuDnxiwfXjG3gzjcdwou1O1e9gmH5006xQTcLVoyi5Ebd6XnXTL9hGCykMe/Qt5FMwoc/DmFPOXxVZubQLToYvKWWzNwYFs8bOhMlZGgVIlCIr0nUJdMaud4la8uugsMv3mSFupROTB7+1vhieF9EPyU+SZ2sspls1mrkAHyD9UuNSvpvp6DoHt/0AClrejumfqoLGSCj8K9hJSa8+H6v7vKfbrI3gmE6cVuVXYODiZfVb27cd/v82AAjYgJLBrOiCiFDxD/EPYux7437DBU5jQk9Rovvk7D3S6eWIaQZBH5eooNqCKpWvrQ/R4/LXGh79tPGNrU86jq1NmrBbNdB2cYGQKdZ46zpQIN/Ytifvogh8BPiw1cpoQuT4cHZyZIZU/EjoHkcNthHJZYYWOZc/bK/Fnlq54Om9D2A3xS9eIeaytFziazNxuB0AzGXHuuiOQs/O2ga3RllcgBHJGFZTkgXFjFvnIGr/ByQWtvxwQwWUM=
MIME-Version: 1.0

----boundary_7370456_bc379558-a15b-459e-90d6-002a27f16110
Content-Type: text/html; charset="UTF-8"
Content-Transfer-Encoding: quoted-printable

<!DOCTYPE html><html lang=3D"en-US"><head>
<meta http-equiv=3D"Content-Type" content=3D"text/html; charset=3Dutf-8">
            </head>
    <body>
                <p>
            Dear Helen,<br>
<br>
Was in touch with Ben last year November - study leave in Kenya and helping=
 family business.<br>
Part of my CPD efforts was primarily to establish a database which looks at=
 the top 500/200 drugs used in UK, and build a training programme to help b=
oth doctors and Pharmacists, also understand buying/stock trends, given NHS=
 cut backs.<br>
<br>
I attach data so far and filtration process;<br>
<br>
1. NHS England - Raw data for several months of all drugs and appliances us=
ed - hell of a job to filter. 2. Identified top 500/200 - volume dispensed =
and clinical relevance. 3. Cross checked with NICE guidelines as to primary=
, secondary and tertiary choice for prescribing. 4. Used open prescribing t=
o check each drug in terms of use ascending over 3 years - deleted drugs de=
scending in use. 5. Cross check to make sure clinically relevant to various=
 CCGS - open prescribing. 6. Used BNF complete to add relevant data to 500/=
200<br>
<br>
I am came to back UK in April this year - the model works- i have tested th=
is in many pharmacies, in particular spread 2 on my excel has had excellent=
 reviews from doctors and pharmacists as a quick clinical reference.<br>
<br>
My ambition is to complete this by cross checking - say for example all doc=
tors in Surrey - so total Rx generated by each surgery, with a breakdown of=
 items per main BNF classification first - then evaluate each drug by buyin=
g trends, cost savings for NHS etc. <br>
<br>
Any help is welcome, work in progress.
        </p>

        <h3>Previous replies:</h3>

                <h4>EBM DataLab Team  (25/09/2018):</h4>
        <div>
            Hi, thanks for getting in touch! Are you looking for total pres=
cribing, or specific items/groups? If the latter, you can use the Analyse p=
age ([openprescribing.net/analyse](http://openprescribing.net/analyse)). Th=
ere's a link to a how-to guide if you need help using this tool. You can pu=
t multiple surgeries into the &quot;Practices&quot; box. If you can't get w=
hat you need from here please let us know! Thanks, Helen
        </div>
                <h4>seb.bacon@gmail.com  (25/09/2018):</h4>
        <div>
            Dear OpenP,<br>
Can I possibly obtain prescriptions numbers dispensed by surgeries in a par=
ticular area, data in respect of past three years - and breakdown.<br>
<br>
Kind Regards<br>
Seb Bacon
        </div>
       =20
            </body>
</html>


----boundary_7370456_bc379558-a15b-459e-90d6-002a27f16110
Content-Type: application/vnd.openxmlformats-officedocument.wordprocessingml.document;
        name="=?utf-8?B?S2FscGVzaCBQYXRlbCBQaGFybWFjaXN0IFJlzIFzdW1lzIEgJiBDVi5k?=
 =?utf-8?B?b2N4?="
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename=
        "=?utf-8?B?S2FscGVzaCBQYXRlbCBQaGFybWFjaXN0IFJlzIFzdW1lzIEgJiBDVi5k?=
 =?utf-8?B?b2N4?="

UEsDBBQABgAIAAAAIQCScEF4pwEAAGAIAAATAAgCW0NvbnRlbnRfVHlwZXNdLnhtbCCiBAIooAAC
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
cmVsc1BLAQItABQABgAIAAAAIQC1TzL14gAAAFUBAAAYAAAAAAAAAAAAAAAAAPdxAQBjdXN0b21Y
bWwvaXRlbVByb3BzMS54bWxQSwECLQAUAAYACAAAACEAwaEL3egMAACCegAADwAAAAAAAAAAAAAA
AAA3cwEAd29yZC9zdHlsZXMueG1sUEsBAi0AFAAGAAgAAAAhAFW4jjaIAAAA2AAAABMAAAAAAAAA
AAAAAAAATIABAGN1c3RvbVhtbC9pdGVtMS54bWxQSwUGAAAAABcAFwDsBQAALYEBAAAA

----boundary_7370456_bc379558-a15b-459e-90d6-002a27f16110
Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;
        name="data - work in progress.xlsx"
Content-Transfer-Encoding: base64
Content-Disposition: attachment;
        filename="data - work in progress.xlsx"

UEsDBBQABgAIAAAAIQBqK1j1ggEAAEoGAAATAAgCW0NvbnRlbnRfVHlwZXNdLnhtbCCiBAIooAAC
FAAGAAgAAAAhAI2YmbRTAQAAewIAABEAAAAAAAAAAAAAAAAAvxMEAGRvY1Byb3BzL2NvcmUueG1s
UEsFBgAAAAAQABAANQQAAEkWBAAAAA==

----boundary_7370456_bc379558-a15b-459e-90d6-002a27f16110--
