Received: from LO2P265MB1710.GBRP265.PROD.OUTLOOK.COM (2603:10a6:401:39::24)
 by CWLP265MB1699.GBRP265.PROD.OUTLOOK.COM with HTTPS via
 CWXP265CA0084.GBRP265.PROD.OUTLOOK.COM; Wed, 7 Nov 2018 07:26:31 +0000
Received: from LO2P265CA0353.GBRP265.PROD.OUTLOOK.COM (2603:10a6:600:d::29) by
 LO2P265MB1710.GBRP265.PROD.OUTLOOK.COM (2603:10a6:600:9b::16) with Microsoft
 SMTP Server (version=TLS1_2, cipher=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384) id
 15.20.1294.20; Wed, 7 Nov 2018 07:26:29 +0000
Received: from VE1EUR02FT037.eop-EUR02.prod.protection.outlook.com
 (2a01:111:f400:7e06::203) by LO2P265CA0353.outlook.office365.com
 (2603:10a6:600:d::29) with Microsoft SMTP Server (version=TLS1_2,
 cipher=TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384) id 15.20.1294.24 via Frontend
 Transport; Wed, 7 Nov 2018 07:26:29 +0000
Authentication-Results: spf=neutral (sender IP is 163.1.154.240)
 smtp.mailfrom=whatdotheyknow.com; UniOxfordNexus.mail.onmicrosoft.com;
 dkim=fail (signature did not verify)
 header.d=whatdotheyknow.com;UniOxfordNexus.mail.onmicrosoft.com; dmarc=fail
 action=none header.from=whatdotheyknow.com;
Received-SPF: Neutral (protection.outlook.com: 163.1.154.240 is neither
 permitted nor denied by domain of whatdotheyknow.com)
Received: from smtp.nexus.ox.ac.uk (163.1.154.240) by
 VE1EUR02FT037.mail.protection.outlook.com (10.152.12.195) with Microsoft SMTP
 Server (version=TLS1_0, cipher=TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA) id
 15.20.1294.14 via Frontend Transport; Wed, 7 Nov 2018 07:26:27 +0000
Received: from relay16.mail.ox.ac.uk (163.1.2.166) by HUB06.ad.oak.ox.ac.uk
 (163.1.154.240) with Microsoft SMTP Server (TLS) id 14.3.382.0; Wed, 7 Nov
 2018 07:26:27 +0000
Received: from mailer103.ukcod.org.uk ([46.43.39.103])	by
 relay16.mail.ox.ac.uk with esmtps (TLS1.2:ECDHE_RSA_AES_256_GCM_SHA384:256)
	(Exim 4.89)	(envelope-from <do-not-reply-to-this-address@whatdotheyknow.com>)
	id 1gKIEM-0003z6-sh	for ebmdatalab@phc.ox.ac.uk; Wed, 07 Nov 2018 07:26:27
 +0000
DKIM-Signature: v=1; a=rsa-sha256; q=dns/txt; c=relaxed/relaxed;
	d=whatdotheyknow.com; s=2014a.mysociety; h=Content-Transfer-Encoding:
	Content-Type:Mime-Version:Subject:Message-ID:To:Reply-To:From:Date:Sender:Cc:
	Content-ID:Content-Description:Resent-Date:Resent-From:Resent-Sender:
	Resent-To:Resent-Cc:Resent-Message-ID:In-Reply-To:References:List-Id:
	List-Help:List-Unsubscribe:List-Subscribe:List-Post:List-Owner:List-Archive;
	 bh=5jmRBqJuZUrd1RKnMKNjl5j2zfPLkEaAiysjqeCkWsA=; b=DAWe/FZigWeGMOtgYigTh3aAz
	s+t41bko7/7ZvqcaHWrsu7kQPDEnG6VV4g5EfKcmQvH3sddCj1V5qDB8YrnQbkQ/a8B0hXoelMJ3m
	qB822Rspp7snRY0F2iR6zUTWk9MM+Yya1ng2az2/hEhL07acQKfsR5hl4IHiFlkKJzm/mctzRHNi7
	cB4TVZhiCc5Ew/D7363fuKLVqlyEfvfOmsOe336yh2GDWMexxnbElpdi9wtteQ6A3fkaWFHZBtMcZ
	Sz42s2mG3128/B/WlaP5zivzkNparMG0PnEkrPm/noa37rSZrxJQbG4+oE9Q+CqC8wI201MjKDtCP
	iTFdcuyIg==;
Received: from owl.ukcod.org.uk ([46.43.39.108]:43615)	by bittern.ukcod.org.uk
 with esmtps (TLS1.2:ECDHE_RSA_AES_256_GCM_SHA384:256)	(Exim 4.89)
	(envelope-from <do-not-reply-to-this-address@whatdotheyknow.com>)	id
 1gKIEM-0006gR-JW	for ebmdatalab@phc.ox.ac.uk; Wed, 07 Nov 2018 07:26:26 +0000
Received: from foi by owl.ukcod.org.uk with local (Exim 4.89)	(envelope-from
 <do-not-reply-to-this-address@whatdotheyknow.com>)	id 1gKIEM-0008W6-Gs	for
 ebmdatalab@phc.ox.ac.uk; Wed, 07 Nov 2018 07:26:26 +0000
Date: Wed, 7 Nov 2018 07:26:26 +0000
From: WhatDoTheyKnow <team@whatdotheyknow.com>
Reply-To: WhatDoTheyKnow <team@whatdotheyknow.com>
To: Emma-Jane <ebmdatalab@phc.ox.ac.uk>
Message-ID: <5be293a27a4b3_47552ae4726ef0ec28342@owl.mail>
Subject: Your daily request summary from WhatDoTheyKnow Pro
Content-Type: text/plain; charset="UTF-8"
Content-Transfer-Encoding: 7bit
Auto-Submitted: auto-generated
X-Auto-Response-Suppress: OOF
X-NTG-DKIM-verify: pass 
X-Oxmail-Spam-Status: score=0.0 tests=none
X-Oxmail-Spam-Level: /
Return-Path: do-not-reply-to-this-address@whatdotheyknow.com
X-OrganizationHeadersPreserved: HUB06.ad.oak.ox.ac.uk
X-MS-Exchange-Organization-ExpirationStartTime: 07 Nov 2018 07:26:28.2440
 (UTC)
X-MS-Exchange-Organization-ExpirationStartTimeReason: OriginalSubmit
X-MS-Exchange-Organization-ExpirationInterval: 2:00:00:00.0000000
X-MS-Exchange-Organization-ExpirationIntervalReason: OriginalSubmit
X-MS-Exchange-Organization-Network-Message-Id: 124760bf-7043-422c-a6c3-08d644825506
X-EOPAttributedMessage: 0
X-MS-Exchange-Organization-MessageDirectionality: Originating
X-CrossPremisesHeadersPromoted: VE1EUR02FT037.eop-EUR02.prod.protection.outlook.com
X-CrossPremisesHeadersFiltered: VE1EUR02FT037.eop-EUR02.prod.protection.outlook.com
X-Forefront-Antispam-Report:
 CIP:163.1.154.240;IPV:NLI;CTRY:GB;EFV:NLI;SFV:NSPM;SFS:(6029001)(2980300002)(3190300001)(199004)(189003)(4423002)(8676002)(83796002)(5820100001)(305945005)(1096003)(3450700001)(8936002)(105586002)(230700001)(3110400002)(6916009)(336012)(26005)(126002)(33896004)(476003)(116002)(156004)(23676004)(486006)(14444005)(106466001)(9786002)(966005)(57986006)(356004)(9746002)(246002)(36756003)(50466002)(4006022)(47776003)(43066004)(46656002)(5660300001)(9686003)(6306002)(41562002);DIR:INB;SFP:;SCL:1;SRVR:LO2P265MB1710;H:smtp.nexus.ox.ac.uk;FPR:;SPF:Neutral;LANG:en;PTR:hub06.nexus.ox.ac.uk;A:1;MX:1;
X-Microsoft-Exchange-Diagnostics: 1;VE1EUR02FT037;1:xUvWAOx5/VR5IPCynGDx7EiFWDPsU9ruyJwsQkU8D345ghxUbe9Vx53BZNDUzeW3uyEKuKRJ84NxMuxMfDLgeIIDNeNqgc0f8PxYv9uG/9icBO41kgVYUd8LijcuDFp4
X-MS-Exchange-Organization-AuthSource: HUB06.ad.oak.ox.ac.uk
X-MS-Exchange-Organization-AuthAs: Anonymous
X-OriginatorOrg: nexus.ox.ac.uk
X-MS-PublicTrafficType: Email
X-MS-Office365-Filtering-Correlation-Id: 124760bf-7043-422c-a6c3-08d644825506
X-Microsoft-Antispam:
 BCL:0;PCL:0;RULEID:(7020095)(4652040)(8989299)(5600074)(711020)(4534185)(4627221)(201703031133081)(8559020)(8990200)(2017052603328)(7153060);SRVR:LO2P265MB1710;
X-Microsoft-Exchange-Diagnostics:
 1;LO2P265MB1710;3:dAHHQ5KjrBHtxzu07vmiHJFnFnLwzCe1AOrmslch9nDafnSZ0ATWMZ1gMAKIyzg+ytJ3NQVJfojAfVjPEDnLmslDdZM3j42Ncbnym4VidN69AQkduFz9svL+uy8nKe6PB+feioBYoZy1khWP/DrGA5RYgu0TbSzTzU1QECVACiGp7zKGMRKuwWCUz+ZrxbVi6WBjWRT21GzUmKW6Hxy7jzB/Hid06DVFweLLLYA+/TfaK7qFnmSNad2KPBAotpJXG/j4y+L0aukbd9TqORerWyLYA+MDHkZzncRF/f/JnBe9FLYTAx7YMo1dN86HFu3fRnw+ESrk6FZBanRCARCD5deXclDLulCQ5PI+k6b2p68=;25:/3g5grKMpb3Wf0WErCD+SD3JBum29CJ4ptFiUhg7xq4rY98btx4qK4vooLUZHz6tNWxzBGvG0jXdk9xb5T3bY8KWipgP+98djvj/GWvUKPoKrKaBBsNvreUWxWpLDx1mUi1CfhGJorIPGeiITrUbbj5268ESYkM3XV7SkPmgjJzi5xd6ELJxyiKoz8g0tAbfRH3zFXSgndZ9A2eArWR/pondTrwtl9jcoW5kbTiKG3LXyKTODgkRQ3K6Y0E8t3aeGImDzr26Kp/Ww5AaUvaeTzxWSoTN0vgmrr4gPOcOYT/RReHtd4vEZ4ypg3bQVkzntcT29TAaE8u51oAcWuUkkw==
X-MS-TrafficTypeDiagnostic: LO2P265MB1710:
X-Microsoft-Exchange-Diagnostics:
 1;LO2P265MB1710;31:jlMsgET4enWdSutlVOPgQvAU52yrjl9VT6zrEcKy7KHIGMwSaobOM5T/rRCW2GZiyDOvGPKqVa6tB0P04fhjoANPyAWDCIDeIsh7ICiRMSWC5KvTYG7itpN1+4xcI7IdzqRcH09C7+FMQfgQWI/v7tcjRqpt/6VZqE11W3ynRSqgLWRk6WZLhVhciJCNADUn3oKBZp9qMvOgkY88bWzAAbWwnEFHFVFG4jICWEN+NxQ=;20:8eN1aMExphqcjAXMwo4F2qU8nGaFrx7+VX8zvS4/v11nyqAa+AwDysKjSpw2/AdVZSgkIUS2vdEEAbNxll0lIgBeSX+KcRas99kIxPf2oBUR22IimSGWQfkszG1jtk85cthnatpmJWuCCxUaJdQ62KE10J69MaDxeJKKQE8tXzSHr8NkTW8vUJAoj3MpVbfEpZqT2wohR6vVIRgYA/E3hU8VafGQcaxdJeAqo2g+AOu7ozSWRPRee4w7HlHZV6/rfkNijSJ4hnFSB+YBj6J2qBcldPc01ikKCwC9XNedP4cc9iGAWk+QeCPOvANun1/BJHFFPl9nWoim6E/mOy0a26DfzTaXXsdFTTwPh7C8BP8f/O4ZJ1K4nmBRFRJRuLTFDwRQ1vF56q18xGtw5UN3rm52HLfSlbSCxKL6E5w/JOU2LgPXEqwdxgmIC3O1RJClC6mFyulOMrQ+8sygD848FpnDTpoVxbXxtEs+e/T65deW4ogU+6vwkHU9Na60H6SE
X-Exchange-Antispam-Report-Test: UriScan:;
X-Exchange-Antispam-Report-CFA-Test:
 BCL:0;PCL:0;RULEID:(2018062399030)(2018011200283)(2401047)(8121501046)(52410047)(2018011210174)(2018011211064)(2018011212028)(2018011213028)(2018011214028)(2018011215028)(2018011216028)(2018011217028)(2018011218028)(2018011219092)(2018011220252)(2018011221063)(2018011222027)(2018011223027)(2018011224027)(2018011225035)(2018011229035)(2018011232269)(2018011233052)(2018021202149)(98810176)(2018021203149)(98815176)(823300264)(823350442)(823411253)(12181506113)(3231382)(901025)(902075)(913088)(7045084)(944500087)(944510158)(944921075)(946801078)(946901078)(9300000249)(9301000214)(52103095)(52102170)(52105095)(52106170)(52408095)(98821027)(98822027)(52401380)(52601095)(52606095)(52606095)(52505095)(52406095)(52305095)(52206095)(88860288)(3002001)(10201501046)(93006095)(93003095)(1610001)(8301001075)(8301003183)(148016)(201708071742011)(7699051)(76991095);SRVR:LO2P265MB1710;BCL:0;PCL:0;RULEID:;SRVR:LO2P265MB1710;
X-Microsoft-Exchange-Diagnostics:
 1;LO2P265MB1710;4:bAO6PT77yMpZ1SKu0H2+VbU8IB91OQ9FFLGpdVbFv8LRYuI8qx5qlDhK9udjpKiTGnlZz+0nS3fzS2GpFWLyxJ4PQtwxGWt4tIoo4WstbnUlOa3SPCRBUiWy4yqg7RQjWOyiJc3k55PtpwlPbOikXvr2zadnfVXt0O32VOqlKHX8g3PFJDBAEGxZhDxVv4+sO8F+k9pLV/6l0p4Y+SfBFuihjslVMJ5bAfWpJhvOpZjIN6NdUBMW+951VBmNNMT/IqWzaXkM9OMMTh5o30yxkA==
X-MS-Exchange-Organization-SCL: 1
X-Microsoft-Exchange-Diagnostics:
 =?utf-8?B?MTtMTzJQMjY1TUIxNzEwOzIzOk1kMFBlb2grNldpbXc0STRENEovWUc2SWZ5?=
 =?utf-8?B?eGNvRHFPQnV6MmFhSStJcEVoUWpPMEo1UHp2bjk4emw4UHBraDNoL0RxcmlF?=
 =?utf-8?B?WEN5OENUcGtQdkNIdHU5cDA3cDNKZnlXRDJlVENGMEZyaFF3alMxaDU1RHl0?=
 =?utf-8?B?SXhXTk0vRXpvSDJVN1JwNjNNdUM2cmtIMDRzZHZmaXBGWStWU1Q0OGZRd1lB?=
 =?utf-8?B?SFpEQWZpTEluemNOajF0cjhTMGxabHhMaFhZWXBZNTlqWDZwcEhaeWtSZGJ0?=
 =?utf-8?B?OTBtQnBFR2RMYXQ2MnhqQUhrTFFGR3QvNFRnaCtJZFlLejJTd2c3TGl4Ulpr?=
 =?utf-8?B?NHpvdGtQdWhXekc1ZDNDbXVJRWV0QnlGMUg2dUQzbnFaNUJSWHRIR1Z6MURz?=
 =?utf-8?B?RVlxVGhWRTh1WWR5czQ1U0ZwRy95LzBSaHpHeG5qVlFGTjRTUTFkR1BSL2dP?=
 =?utf-8?B?bXZGb01XQmo0Mk1PVFQyS2RsK21JR2NmQjlSM1BHd21uNVBhRkI3bWI5RGhI?=
 =?utf-8?B?R01kb3h6OXV3dThaVGt1TWpYZ0hNM1JrYlZ2UHFSWm0wZVRFdUxOWnAwZjBD?=
 =?utf-8?B?OXJkQ05tMFJhM0Q3dE9EZE1MME83TUM3OEJRMmE3Z243eXdMeDEyZUxKVEE3?=
 =?utf-8?B?Z0Q4ZmdvS2JKbjcvc0RjQkt2SzJiRlhrL1lHZi8zSnd3Z003LzkxMWNRWUlW?=
 =?utf-8?B?TWExQ1RlUmJ6TE4xNjZkQ3lZaFRacmlPRmliTmhPOEJaTi9XVnYwQndNRU5o?=
 =?utf-8?B?RWVQc0RlOXljK1JtMkgvaldQSkgwc2U0eHlXV0ZwKytWbDRtOHR4TEdEaUpC?=
 =?utf-8?B?NjE3TFNBcHZOeE15WGFaZmNKSEZjbWN3YU9HdVBxUFo0UWxnZ3lud2hYdHYz?=
 =?utf-8?B?L2lHODlhZGZtdDd4ZkFkcUQvTU8rY3d0bU9BQXUwWHFsQ2EyRmlHWTZPS0Zh?=
 =?utf-8?B?WjI3bEEvblhsRDlGQnQ0akpnNnN6Ym5vbUptcHh6U3l1MkZuTDBmK2RTOXJk?=
 =?utf-8?B?U0hXQmQyNm1ScHJJakhHaDJKbHlHYmViMXhmYXNydHJFTHFZY1FLa2JQdU16?=
 =?utf-8?B?T2Y0eGhDUDBNci9pMTVQeTVKUzIvTXBRTVhsQUs2aUxVd1BSSVVkUXB2b1NV?=
 =?utf-8?B?Vy9qMDEySGpDRitTS2phL2xIbS9LeGQ3enpaYWZHcHdSR1o2R2hlVXEwVHo4?=
 =?utf-8?B?TlNTd0FwR2NES1VEUGE1NEZTWDZsdFVmalBsQTEvTFIrWEJtOUxYaWNZUGV5?=
 =?utf-8?B?cUM0aERBODkwMFhCLzFCRkNxS1BYY2ZVN1NhR3VCdU14L1dubjQ0WDlDbFhQ?=
 =?utf-8?B?Uk1MOFoyUzhnNmZueDBabTY5UnF1RmFNZG40L2EraEpFcnRhY2tqaVNTSWxa?=
 =?utf-8?B?NzJiVTF0TjRaMGJBWXF2ODNUeHJJeHVNQ2dnNm13PT0=?=
X-Microsoft-Antispam-Message-Info:
 ItqmtGhK5rQLlfJHtEmhE0qcffg7PwVNTWYbZcT70EpETwUYhNsozwNGSEkzk4KaURwks+Kaw9OX/8HKeEEJubnSfNMr8oJ+LZCFM+KU204E6jz5nWooks3iH/3W965Bo3nKG6z0hJwRxDUTqI8WSzalhXB52oVO69iLocF7ehb1kW8Q+4QK0mMKJJQltRuRQH9A5KwWrtRg9anW39beJ8R0dGDKkzcZZSz/7ShTZZVdKIxFkhk7w+U1IYWKgQEwZyxk6DdphHBnTtL6T8hy/yCJ0zpTVP7giqeX/F8aKI9Xdb5W0FIp5Rw6R1XbtCEc2b5Mctxe/s/CEUL4LyN0fhUf0BfZcvus+LKLFnXZVdspEEUOb4CVPl4+0gswo29G14rOz+5sE1LHjhB3/VAK3WTsOLZIqGTLan4RZH3Et8hsKWNN3LLipwmd1E7Ymdh5RGtgmsxdo/0yXCk8CYGDaPYV+2skU/BIGUGAR4Wk/w4q4V0AJQgK5+lDZt+KaB0G9Jseozhs0cDoJ76yTWY2JdA8J2R2mdU//0OTtpxoC2O1i360Hm6wYc5/lWOH9NuIS6XjE7YMriRwWH6EteEpMgeyUFiYpVvYGTPFxUzzGLavaVGZgiabqKQr5qMf96JpBr4WKf8zOy/HrxS9uI5HsUZB0KEqlyW1Rk3yjJ9RGteSiuxA0hONCfwR3ci4OvxcM/xVmmISXyz0PLxByMzWDCa5TTCOrjGteHC6gLe6JhM=
X-Microsoft-Exchange-Diagnostics:
 1;LO2P265MB1710;6:w/15+/Tra064ZvCCIKTugJG9qAsSWSEtBsGxeeZuXtMSYxrHUyBAzUFxt3PJ7MvPCEdnDCM4+v4FXWw4NH40RcltDB5XV+MfeuSmtcJgS/FsCuvp2oGlCSuw1rdUypJfp/ar6eZ0Vko95spA6NioC3lsHutlo871V2p+yS2SyqcdcASkY8dmQQFfU04GgVO1DHsa0oiwml8T0i7qkTrCbSuEkl9VQZDl7Wa4bd/1LkIQNoELL7AfPBAmrd562M5dq5khNpZZcOladTO+EDs98mvCBr3Bl7puLRrZBJmOksmLmXwXsQooIqvN7wOAae+kUCpIiclh3NaZuGFvA18xy1Y371yd9KwLeimZxZ5bUxjpVvOmAfMjr082h+eN5AOZfakZbDsG+Nh1lNxhNT7kOQYCRoblHZmMwpj6Tfkh0pXwlxjAHu201XyzZy0CxmYbluqDEKyrHdd4Pit0X6jihw==;5:mmLZ2+k2zAi2I15GkG1D/xAXldmVWiz/MEJOqS7tI89tgIKyAs/5REFPaqdumiSXtwbuNfI/n8iWW88cWPPHTndUJQP1IiHF+XtYudn3rVxwHL3owTUtfHGECOG3NKK9Ng0l0NvAFoyqp7Wlh7ryExakAqtqPZcy22zf8/2Mr1E=;7:cSmMPQnLQPO3i0TXroJx7qiGRDq9/BM0N2pFR2sTVjJkJfpzcCIZ+dxOBPat4dfLNCYrQDzLHPCno6KL9f3G8J3qA/hmwMh8bTrpGfWCbiH9Qdi4f1chPEfWBHfmrRXw7P9X0hxXj9Aiyco0G1ZiiA==
SpamDiagnosticOutput: 1:99
SpamDiagnosticMetadata: NSPM
X-MS-Exchange-CrossTenant-OriginalArrivalTime: 07 Nov 2018 07:26:27.9784
 (UTC)
X-MS-Exchange-CrossTenant-Network-Message-Id: 124760bf-7043-422c-a6c3-08d644825506
X-MS-Exchange-CrossTenant-Id: cc95de1b-97f5-4f93-b4ba-fe68b852cf91
X-MS-Exchange-CrossTenant-OriginalAttributedTenantConnectingIp: TenantId=cc95de1b-97f5-4f93-b4ba-fe68b852cf91;Ip=[163.1.154.240];Helo=[smtp.nexus.ox.ac.uk]
X-MS-Exchange-CrossTenant-FromEntityHeader: HybridOnPrem
X-MS-Exchange-Transport-CrossTenantHeadersStamped: LO2P265MB1710
X-MS-Exchange-Transport-EndToEndLatency: 00:00:03.2644111
X-MS-Exchange-Processed-By-BccFoldering: 15.20.1294.024
X-Microsoft-Exchange-Diagnostics:
	1;CWLP265MB1699;27:bQ42ECncEcQND+FBpCzfcBQIstN1E+1ABAv1FW+8E1oYlZ50/jTpST7/TzKnfWn+ndkZh3WiHRZjsFZWFTdhgKFg3aZFETM8Cvu1IjJcn8NewEIdBe9jEagC1q5sUizyjS4zuw/pvcgMcVYzuQP8swVYBF+/eNpOG/dJwGZ9oMPK192oQr5sD/HKyLtXD2oI/Hf+XSnWJ/3BQfQ4F+h9zUFDGGtje2nFFJ2weV/P84+J1X5UFMIGtDeReNhK18ZiuPJkHPuJN/9M0IzqMdTDuKxgbVxFNsW+ORGL0nvUGbfvYreT9TeZq5U2Pw1PtXpV3bRhvsVxYz3D1mewhkCg+jZTWtomwfcXQ0N/XJEPpVfSfE6OzDJHUNvNpwUYH6TmkAGAa3h6zlU9tbEegFDoRA==
X-Microsoft-Antispam-Mailbox-Delivery:
	ucf:0;jmr:0;ex:0;auth:0;dest:I;ENG:(20160514016)(750119)(520011016)(944506303)(944626516);
X-Microsoft-Antispam-Message-Info:
	hQ68i5asWoOWUF0P9px8ccHjEdBtHVIX6aMrtjDSL7jDxfXvt31OM42uL1+pmnMjJL3MWX98F0NDX69oUdhCoR0pyRZ/WDEyPHyNYG4Vi43wdHxCl80bp3hP478ME4LTnxNGYpWYLXfTw9IMTse+BQ2yPRUaseSwxec3uEB1/MHk7XiR5gsFGc36pCiRc7/2xiCypljpICy4JgzfSR6dipp8a2vNiDIdiLdzj9H4ndLT4lxM6Nl1SjcQDtiMZXlAuCWxt+PEDcJ1D2ZXNtkPJXA5H6fMDpub/nNaRMhJ+ngFfbhLsErlwqxw3CyGlqAwN3VSPmnHLvxEAVWONkzUHG1FumzBE5RXKQDc+CuvHVIJbLzlhGQSsdio4LUYIkFEIXirC0gSCkJTKwoVTI45KOrFfq3MACThrp3ieDt6gM9LJ2Do9M898CK+nButePis3xSPnYRM7T+0Eth8j6mwoYKuoM6Hv/RRtgC/3LTD7zi6SM8NQcQkMn4LnzdlgjZ89JUJsay4XR5jZpLAVxc9jB5n380J6R4GJCrd+/hvussDq2Nv4IlZiuhwu7itkLgjK4ZLyBDi4hgvknJkIh6JDOEDjPgu4DEB5+dC+4v5+eDITibz5vNfi68aRmVfD2IEPWm5ut352ssZXpmriFuN7Gan0LGC2HOHvpf9Cg4EODSd1N+e5sJjKMpU8//uw/lvjSTpdFlPv1KnFPX++2wHYIyJSFJXhIGYlnMwCiKp4WPVH2CAR+iXCOCh1fljOikCq3G03qAjHeeANOJhejaLjiqbemnQm2dsb/l9cDVLSppZOwaWMhsAYSyauX1LGaiP
MIME-Version: 1.0

Here's your daily request summary from WhatDoTheyKnow

Documents related to Drug Tariff inclusion
------------------------------------------

2 recipients, including Department of Health and Social Care and NHS Business Services Authority

1 Action needed
1 Complete

What's happened:
2 requests had new responses:
You can see the responses with the following links:
  NHS Business Services Authority: https://www.whatdotheyknow.com/request/documents_related_to_drug_tariff?nocache=incoming-1260611#incoming-1260611
  NHS Business Services Authority: https://www.whatdotheyknow.com/request/documents_related_to_drug_tariff?nocache=incoming-1260598#incoming-1260598



-- the WhatDoTheyKnow team
