Received: from CWLP265MB1700.GBRP265.PROD.OUTLOOK.COM (2603:10a6:401:5e::19)
 by CWLP265MB1699.GBRP265.PROD.OUTLOOK.COM with HTTPS via
 CWLP265CA0367.GBRP265.PROD.OUTLOOK.COM; Wed, 7 Nov 2018 07:34:00 +0000
Received: from CWLP265CA0008.GBRP265.PROD.OUTLOOK.COM (2603:10a6:401:10::20)
 by CWLP265MB1700.GBRP265.PROD.OUTLOOK.COM (2603:10a6:401:35::18) with
 Microsoft SMTP Server (version=TLS1_2,
 cipher=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384) id 15.20.1294.21; Wed, 7 Nov
 2018 07:34:00 +0000
Received: from AM5EUR02FT057.eop-EUR02.prod.protection.outlook.com
 (2a01:111:f400:7e1e::206) by CWLP265CA0008.outlook.office365.com
 (2603:10a6:401:10::20) with Microsoft SMTP Server (version=TLS1_2,
 cipher=TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384) id 15.20.1294.21 via Frontend
 Transport; Wed, 7 Nov 2018 07:33:59 +0000
Authentication-Results: spf=softfail (sender IP is 163.1.154.217)
 smtp.mailfrom=ebmdatalab.net; UniOxfordNexus.mail.onmicrosoft.com; dkim=fail
 (signature did not verify)
 header.d=ebmdatalab.net;UniOxfordNexus.mail.onmicrosoft.com; dmarc=none
 action=none header.from=163.com;
Received-SPF: SoftFail (protection.outlook.com: domain of transitioning
 ebmdatalab.net discourages use of 163.1.154.217 as permitted sender)
Received: from smtp.nexus.ox.ac.uk (163.1.154.217) by
 AM5EUR02FT057.mail.protection.outlook.com (10.152.9.242) with Microsoft SMTP
 Server (version=TLS1_0, cipher=TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA) id
 15.20.1294.14 via Frontend Transport; Wed, 7 Nov 2018 07:33:59 +0000
Received: from relay11.mail.ox.ac.uk (129.67.1.162) by HUB02.ad.oak.ox.ac.uk
 (163.1.154.217) with Microsoft SMTP Server (TLS) id 14.3.382.0; Wed, 7 Nov
 2018 07:33:49 +0000
Received: from so254-23.mailgun.net ([198.61.254.23])	by relay11.mail.ox.ac.uk
 with esmtps (TLS1.2:ECDHE_RSA_AES_128_GCM_SHA256:128)	(Exim 4.89)
	(envelope-from <bounce+0b97aa.3e09fc-ebmdatalab=phc.ox.ac.uk@ebmdatalab.net>)
	id 1gKILU-0000nG-b6	for ebmdatalab@phc.ox.ac.uk; Wed, 07 Nov 2018 07:33:49
 +0000
DKIM-Signature: a=rsa-sha256; v=1; c=relaxed/relaxed; d=ebmdatalab.net; q=dns/txt;
 s=krs; t=1541576027; h=Content-Transfer-Encoding: Content-Type:
 MIME-Version: Subject: Message-ID: To: Sender: From: Date;
 bh=5xmfmc+kJgF2D0k1EAsKw+xYZX4z8geE4kEES5+QLN8=; b=gcP69/ZlN+rcM48TBySOGLR8+AkUIZ7k+xAosb5HmXM5XHJR7/FCVLvTvyAGF+JtCgYHHUoO
 qgH6tUq1tP4xV9NtnYfrTI3JLHQbh98qwL1v5HRNv1suKObBM+Ch/0zgEPGbNHE29ChKhg1V
 rohGjhdxoz/f8KHGRLBrUky4xfE=
X-Mailgun-Sending-Ip: 198.61.254.23
X-Mailgun-Incoming: Yes
X-Envelope-From: <ujauxau@hlmod.ru>
Received: from ALT1.ASPMX.L.GOOGLE.COM (Unknown [114.96.250.209]) by
 mxa.mailgun.org with ESMTP id 5be29559.7f2624653e30-smtp-in-n01; Wed, 07 Nov
 2018 07:33:45 -0000 (UTC)
Date: Wed, 7 Nov 2018 15:33:27 +0800
From: piaoqiaopanqiang <piaoqiaopanqiang@163.com>
Sender: ujauxau <ujauxau@hlmod.ru>
To: hello <hello@ebmdatalab.net>
Message-ID: <20645942.3765785.1541576007459@ALT1.ASPMX.L.GOOGLE.COM>
Subject: =?UTF-8?Q?RE:=C2=A0enquiry_/_electronic_components?=
Content-Type: text/html; charset="UTF-8"
Content-Transfer-Encoding: quoted-printable
X-NTG-DKIM-verify: pass 
X-Oxmail-Spam-Status: score=3.7 tests=DEAR_SOMETHING,FREEMAIL_FORGED_FROMDOMAIN,FREEMAIL_FROM,HEADER_FROM_DIFFERENT_DOMAINS,HTML_FONT_LOW_CONTRAST,HTML_MESSAGE,HTML_MIME_NO_HTML_TAG,MIME_HTML_ONLY
  0.0 HEADER_FROM_DIFFERENT_DOMAINS From and EnvelopeFrom 2nd level mail
                             domains are different
  0.0 FREEMAIL_FROM          Sender email is commonly abused enduser mail provider
                             (piaoqiaopanqiang[at]163.com)
  1.7 DEAR_SOMETHING         BODY: Contains 'Dear (something)'
  1.1 MIME_HTML_ONLY         BODY: Message only has text/html MIME parts
  0.0 HTML_FONT_LOW_CONTRAST BODY: HTML font color similar or identical to
                             background
  0.0 HTML_MESSAGE           BODY: HTML included in message
  0.2 FREEMAIL_FORGED_FROMDOMAIN 2nd level domains in From and EnvelopeFrom
                              freemail headers are different
  0.6 HTML_MIME_NO_HTML_TAG  HTML-only message, but there is no HTML tag
X-Oxmail-Spam-Level: ***
Return-Path: bounce+0b97aa.3e09fc-ebmdatalab=phc.ox.ac.uk@ebmdatalab.net
X-OrganizationHeadersPreserved: HUB02.ad.oak.ox.ac.uk
X-MS-Exchange-Organization-ExpirationStartTime: 07 Nov 2018 07:33:59.8956
 (UTC)
X-MS-Exchange-Organization-ExpirationStartTimeReason: OriginalSubmit
X-MS-Exchange-Organization-ExpirationInterval: 2:00:00:00.0000000
X-MS-Exchange-Organization-ExpirationIntervalReason: OriginalSubmit
X-MS-Exchange-Organization-Network-Message-Id: 491eb20a-1164-497d-36f4-08d64483623b
X-EOPAttributedMessage: 0
X-MS-Exchange-Organization-MessageDirectionality: Originating
X-MS-Exchange-Organization-SCL: 1
X-CrossPremisesHeadersPromoted: AM5EUR02FT057.eop-EUR02.prod.protection.outlook.com
X-CrossPremisesHeadersFiltered: AM5EUR02FT057.eop-EUR02.prod.protection.outlook.com
X-Forefront-Antispam-Report:
 CIP:163.1.154.217;IPV:NLI;CTRY:GB;EFV:NLI;SFV:NSPM;SFS:(2980300002)(3190300001)(189003)(199004)(5660300001)(5820100001)(305945005)(106466001)(105596002)(246002)(6666004)(156004)(86152003)(88526003)(356004)(55016002)(26005)(6392003)(7846003)(61726006)(956004)(82202002)(6246003)(476003)(126002)(116002)(6862004)(486006)(50466002)(7696005)(336012)(42882007)(23676004)(9686003)(413944005)(61266001)(63966002)(23846002)(4006022)(8746002)(1096003)(8936002)(13390400003)(3962001);DIR:INB;SFP:;SCL:1;SRVR:CWLP265MB1700;H:smtp.nexus.ox.ac.uk;FPR:;SPF:SoftFail;LANG:en;PTR:hub02.nexus.ox.ac.uk;MX:1;A:1;
X-Microsoft-Exchange-Diagnostics: 1;AM5EUR02FT057;1:oOwxJHx8YpydEY5raKAWIP72HPeKGvELhNVFrdSYCXXN3u3SAh4rv8iLCgSKqa8EP9oHG7sCpAorTc66+N563Y6Hn3jRFWQlahZ65xvwgAZNBvB8O1vBwlnOfSHpk/lR
X-MS-Exchange-Organization-AuthSource: HUB02.ad.oak.ox.ac.uk
X-MS-Exchange-Organization-AuthAs: Anonymous
X-OriginatorOrg: nexus.ox.ac.uk
X-MS-PublicTrafficType: Email
X-MS-Office365-Filtering-Correlation-Id: 491eb20a-1164-497d-36f4-08d64483623b
X-Microsoft-Antispam:
 BCL:0;PCL:0;RULEID:(7020095)(4652040)(8989299)(5600074)(711020)(4534185)(4627221)(201703031133081)(8559020)(8990200)(2017052603328)(7153060);SRVR:CWLP265MB1700;
X-Microsoft-Exchange-Diagnostics:
 1;CWLP265MB1700;3:25Ny3EipKIj32EsuxOhA+I26NwGTeyIrcqnpgHYeonxroXyZEegYuVagSh43o8DgpaZlbNAMcD0dknrMgLLVKq/QGsNS0pu04s39xqg0SV6XLTjfoVTICHLxnOoZiuxdfb4OYT3d7XqFD3SbaN9edDtJOVibWok9PRVjWKpyQlc33vYVPcuzkA2IEJycNxtXN8s7880mFVQbuX/oQ5jYHWjBvmvzdRqYnxnoD8wrNflwKCvqrziJVq8aAYyDIjRP+AShg71g9wNInyo6eCqNAWi6p8bFoLccsyLhkvbjRCbkk8GMMWGlqGl67icXMoPSfJjermZo6Y9DLiYVksFSQ4OVZJ/UPbYojq61JHPn8KQ=;25:Z5MKrlECE6G0YCe5U3Y6DcxfzQuKLSAo+C5KkD0WWwt1+Z7Mv6MNTsnqN/aKKjs8xB2deyFZdmHTXABMQwawKapbZHZfjbsiBn6yiJm+5PUF58yLRb+IDuvvZ4G8Mk3X5VhlRWvb02BTAmpR4IWdY8LiIt5A4lFAAwx35PVj1REJb95Rshui3XHaS7DVZCUHude/7Ct/zsbGGyRsHneGf2GWLqf56HRWXcaBVl29LHHTPYsOIzZrItp9ILHiSPfSqGVSaRslB5ZmbpG1l9uJKoq7ZA4cA9cHgbbky0KHcT45nDlMTZIB3xtS8Wmz4Eg2s0sC6ZwqWKylv2cw2GYnug==
X-MS-TrafficTypeDiagnostic: CWLP265MB1700:
X-Microsoft-Exchange-Diagnostics:
 1;CWLP265MB1700;31:Y20YHBpP9mwKtHc7RrWoyy67PAFmdL6zCS0JiqQfEVjUawUvBVz09BBo8xGOcoNk/+Fd/pjhNyKpw1HPD4rcs3cIIbZeVunp4p8BlVw+PiS5e+ffKaklrMHDT/AXVVs+h5Og28wf6avLSkpqEEZ327mzA2Ehd6+Hw7/UrVw8NGRSGzA/B9h2dBcOOmf1CheueTHcEHS3OUdCTGmN5XGfLpe4xndepi3LcmLF3E3/Edg=;20:tQH+xmz0qq1LLLFB1604xZjfu1Z/Lrgk15Dnpmqly7pq0/VSit0xo+68oRgX8gQ7tFiqStfaIxBbpKhtGH2HgzR1tNfcjfnL7vt/6ZSAnAGvtT9UQXXJBmWPa4OR1iE0Fqzuxsz9CBWRSJLXwLTubKAkajGUMWtvqGi5FhY2T71wimobGhCgw8z+rbIYkJOHKR0qBfB+Auw4bjS46axASGwQCBvDgk4JlV2Ng1QSWbM5ZWsl2Hybvi0Mir0bm1ohzkufKPTgXqBd7yeUf247dinbxXORnZKL1Un6GYze3xDjwunt/op2TEhh3RjU+15e8MtTYEWQvTgKkwTlqReLAQ==;4:+WYluyUHG1M8eJRm4DTQDahgv01Uc1PuvgBeir5q3dOmuoPDMmksgNXfmbsNHqFLQDAbyEiq7Kf94WdgEusfj85NFXCAwqKzL/rkrVVhEbIPzx4qF80sik1IdfvNqef+dbPaPqtTZmXn2hJ7WBCNFRlTG9HoDzphe9BGLX1Sm/h1HMJusAsoa+hE+XShAhNtO6ZsVJDlk5m3pGCKKoUV5rBGwMAObS651yMteOdHlt8AjeA7EbgTy25sC6b24BWUnS4pJmYHRTdpdzYtjvHbRA==
X-Exchange-Antispam-Report-Test: UriScan:;
X-Exchange-Antispam-Report-CFA-Test:
 BCL:0;PCL:0;RULEID:(2018062399030)(2018011200283)(2401047)(8121501046)(52410047)(2018011210174)(2018011211064)(2018011212028)(2018011213028)(2018011214028)(2018011215028)(2018011216028)(2018011217028)(2018011218028)(2018011219092)(2018011220252)(2018011221063)(2018011222027)(2018011223027)(2018011224027)(2018011225035)(2018011229035)(2018011232269)(2018011233052)(2018021202149)(98810176)(2018021203149)(98815176)(98814176)(823300264)(823350442)(823411253)(3231382)(901025)(902075)(913088)(7045084)(944500087)(944510158)(944921075)(946801078)(946901078)(9300000249)(9301000214)(52103095)(52105095)(52106170)(52408095)(98821027)(98822027)(52401380)(52601095)(52505095)(52406095)(52305095)(52206095)(88860288)(12181506113)(12181509095)(93006095)(93003095)(10201501046)(3002001)(1610001)(8301001075)(8301003183)(148016)(201708071742011)(7699051)(76991095);SRVR:CWLP265MB1700;BCL:0;PCL:0;RULEID:;SRVR:CWLP265MB1700;
X-Microsoft-Exchange-Diagnostics:
 =?utf-8?B?MTtDV0xQMjY1TUIxNzAwOzIzOkdwd0N4bFVoa0Z1dUtNRGk5Qi9VaDNOck9N?=
 =?utf-8?B?RFBPZWhOeHBvbEUyOHVRZnBibFdCOXczTnBVbmFLUkR3clZES1BBZFhpOTla?=
 =?utf-8?B?UjhVTXJzR0I1cGZvQlVlNVhPcFpRMDl2T3ZCcm03eDN0bjArOVNQcmtsSGdE?=
 =?utf-8?B?WGpCUFp6NE9lME1tUnVuQ0NHMkc3NnhjcEE0NkJSelc3NWJKNHc2SUxJZFgr?=
 =?utf-8?B?aTd2aTVQaU8wR3ZQZ1NodjJaTlN1ZTAvMkVScXBOSU1sUWpnNDRLSXk1ZkdF?=
 =?utf-8?B?RzhBakZrUi9tZ1Q4c05CcVE3SEVmSXY5VkljS1dIR2F6UGJiazZ4VHhXeHZV?=
 =?utf-8?B?TUF0QTJHaDByOHpvM0FLSTRwaFZpU2NlWkdJa25NR2pGKzZTRzJxNzlvanFs?=
 =?utf-8?B?WW54MHZ5RFRHZkI4Ly96cjZKcFI5WmJ0UVFQNHgzKzhOQmFHL2ZtMVduM096?=
 =?utf-8?B?akV6RDk2NU1iRGRkOWd5SEZqUGNSMkZ6U2EvYmJRaFVGMkFBeW9IbytBZ0JK?=
 =?utf-8?B?c2Y0czVVUnZyOVd4eHB4L2UxN1MrMWxoaGo1aDZBTzRLbmF6ZUxQUjhnbURl?=
 =?utf-8?B?Q0hEeTBhWXB5MEE3dWVZWDVsVTBXVE9LTlg4MGhwSllaSkgxMzhJeDI1VzBM?=
 =?utf-8?B?RHVGcHc4TG1wUVAvV2NHUXZtOEV4TW4wa3N4V0xGV09EenZ0TXdzWXg4UzFs?=
 =?utf-8?B?amhkUmdINkhJdEdkZHFaRkhvZXgyTStGREhZM2FmMDFYR0dXdXJZdmVQS1dK?=
 =?utf-8?B?NjkzUjJJR3hHcVRmaVhiWkxleFlzZllSS3NZNElONFlITzJRWjlhR3lxLzJl?=
 =?utf-8?B?dUJmMlZBbksxS3h4UFRBWCtJcHFOTkRqUUV1VnJBb2hsVCt3cXF3eTZ1M29M?=
 =?utf-8?B?NFNXRnNUSWZ5b04xcVFuSXI5Z0xzNVBnY1I3UEZYZDdjVEw1NXdvT2NlQ1gy?=
 =?utf-8?B?Tk5UTTdpU01odkpqWWZaUCttZktPY1J5Y1RweE5BQ1kxQkEzTXNBZjQ1TVo4?=
 =?utf-8?B?RG84TGsyRWRvUjFBOHBYeG5IOGwxYzY0TFhibkhBNFdqZDFMQnVJUnMvYW5M?=
 =?utf-8?B?UTRJWi91TmtFR1REYzU3eWV0a2lDZFVOUjlWRXJDTGMyNHczNHg3QmVaTG92?=
 =?utf-8?B?YVdYVGlmMFpkQzZIM1paMHowcXdSb3c4bmxDSGpGTWhGWExNTytKb0N0RjJU?=
 =?utf-8?B?M3JrTWZ3aGh4V2NLOUdwZXFudnBNSnh1NDBhVXBWc0xMaSswTGx6MmNIM1lk?=
 =?utf-8?B?SFQ3WXZxY0V2aG83RFNnK3doS3J3UFd6dlJkWnNwUWpOTHdVczNJT25xblJH?=
 =?utf-8?B?TCtvTjJYTmYyOFJjRzZoaUZnYUxJSVppQk94eTE3VnZ1SlRhcExEeUxPa2Fu?=
 =?utf-8?B?VEUrZ3VXRWlQb3ZwTStkbzZnVXowUDNxeFM5Q1hnPT0=?=
X-Microsoft-Antispam-Message-Info:
 Xt/jRubct48pvg/g30a5zKJik4Wma2bwEHgxT/WukTzo71hkRPu6MZBiK56CtQt/1Beg+ABTdtL0PygvkHMm4Y1qjqGz6PmTI3L3lRm/oTanSytnM4hOWUmnGNFs19peGLQQIdCb6DQjsSOcTU3bP7+WjusnopJj/dr+wuXWy8NJrnWQx5GSz41DLqLqk8Lp5cU2sty85zL3wcfIK6DOXi1ERSUbA9BXlnStUehgeSO7vrhrWy92z6g5z8y0QiDq4gxG4ey0dP1Y6PthngeFZLD0xMOYDkb1DyIY19JQOWlqomBGo3vB+Pmm462T7rhRYTZrUDFH7UPA6XnjuS+GXl8STRK4CQDrUCeBAxOTEGN8axXWxbC3kur0Xts3r7Y/6gQBTNDG2ECouJRRppwGSVgd+bQmXk5OYXroxE4BzgpeidtNhtDikeMSxyvrhFmeJQq8SbIyj92ABcv5GAR7/m5K2ICS34r3lqmVH6U/kX32YR8buKQrMqedLzEJ9/8m4ncQtJgVHLUR8LXj9YOH95CfJeTCi2Il5iXcopqNckJC0sk+egicrS/jaCdghjjVgMzK06TxEzaJEL05Tw/k3hkypQcCGNR+i+z9VCzhMphOUUBv5bIwLuH7uSlSR9JMOxIvzo00ib/dwhEAoRRjgP/kTak9rQk99O0Tu+iXx3NJJwRJ/mBPLtTR0lqnEdtG
X-Microsoft-Exchange-Diagnostics:
 1;CWLP265MB1700;6:tmn88zlQjgNwdkCkjsuGc4cCviUPdcB/Ylxj1o671kHUXIALFwMxGNSpLs0Nf1g0bDGQAB8YEVi2hftkdAHH/c4/L+XzBzmiaJ3xyEK9pHXoREBECIPrbBtjT32Cg8s2u4a686hbaunBj2AE9jjB5gbQyxc52wx++tVqaX76JTzRiFgj41VQH+1NC2ywPyvLNW9k3xi9lWsCU+QwDy1eNQdBDAN7C1OK5hjJjeHWcvAMYCnkQm/lb5UZndh5ORgribXRcDNwHV/s7x0DvgV2zRKBORJ2cZltW1fgprdBPzX85aTBxN3qBB7aeRhZ0zhdipT55vUDOgl7a9Gc1Pozcs2D2sTnqjagLBJHj5Oif0y4UdsQvGHzpnPXcjJxlwxzAZ91DAMHtTVIeGbLIjt9FhHdhjMyMIRAivO3d6kSv7uvr4fY2PMr5b0Zf9YQw/l8iL/nDnDOyHq1w1wYuDSsSA==;5:fo4uzJLTgO53owBqx36LwYAu0IrqVta005XIUkYX4JVBLCJJhQ4ntMN6l6xQtk4Yyh+yfB5CzNoXTRoKNHWZEKPZPP/0Wq/GF4Rp0f6sLJU7jlo4ztmiuqLxcbLVO1NyFv5tCE74laFal9BUo3cUcf0IfjoOgQIT5RdKOhtcVVU=;7:PC+PlrFEy88zWq11WxDVnxvUEY1QJaavxmIaIAgPYgKw3e0qVLtvblU33cjxk3qNxsirvDfuMk7hVtDqUkbLzXptnRuOHkLRvh8nFHDOsukghz49w4h01Sbu+K2FoNTmSw0NeFOy9Q6SxGmQAQ1BHQ==
SpamDiagnosticOutput: 1:99
SpamDiagnosticMetadata: NSPM
X-MS-Exchange-CrossTenant-OriginalArrivalTime: 07 Nov 2018 07:33:59.6456
 (UTC)
X-MS-Exchange-CrossTenant-Network-Message-Id: 491eb20a-1164-497d-36f4-08d64483623b
X-MS-Exchange-CrossTenant-Id: cc95de1b-97f5-4f93-b4ba-fe68b852cf91
X-MS-Exchange-CrossTenant-OriginalAttributedTenantConnectingIp: TenantId=cc95de1b-97f5-4f93-b4ba-fe68b852cf91;Ip=[163.1.154.217];Helo=[smtp.nexus.ox.ac.uk]
X-MS-Exchange-CrossTenant-FromEntityHeader: HybridOnPrem
X-MS-Exchange-Transport-CrossTenantHeadersStamped: CWLP265MB1700
X-MS-Exchange-Transport-EndToEndLatency: 00:00:01.0607737
X-MS-Exchange-Processed-By-BccFoldering: 15.20.1294.024
X-Microsoft-Exchange-Diagnostics:
	1;CWLP265MB1699;27:WO8OhQjl5PajZx91XWzWTbOiY5t8EHilgOjUu3GPcjRaeyWh3IGn2dT8Do62FfSFIy2zGDNsM/nK+li9Tmyi+W3/223HfXwZA6GFjAWwTOdkrz4kTaR3g85eBskTX1aWhIU9aMnwtjVKPXy+P/wWF6eCk04wCVFvciYjuhm2RWWoGRlq3hbuH4VCM0lv3KVGFszyTknk1LxRvIy50Nuzc3HYZjzNzn79qZWB3AxpkC4dFhv0OlNPA9CxjeKngtUQ14SGGYNwuf9ZoG9btMuB2y5qXxsNpeDw0j0l84KNuLqIaJSvYoV9h6ybKaUnNx7kPTKlcvtCch9Do8lVwWmd8iOOlDoxqmA2X8c6RjMCWzsyOh2nV2TwVKfljUwUjq8M0usnjrLX3Aa6xSiGcMC9IA==
X-Microsoft-Antispam-Mailbox-Delivery:
	ucf:0;jmr:0;ex:0;auth:0;dest:I;ENG:(20160514016)(750119)(520011016)(944506303)(944626516);
X-Microsoft-Antispam-Message-Info:
	+Vf/h00xWzLYwa3Y8j+aVcTzDUSZ9nsP0C4u28WbGQYQ75MssW4bOq5K+6XqtgsrXB+GMXLx06ukuBiuKZM2JBjmTddYcxGYN6AKt14mXEWJin4AAyPL3Y+4eFPFjU9cgbUhOoYJq3Fz3GWTmUV8ieAGz2zCqE5VtFOCtIFkFhL8yIVYuxGbGOZ/M4aVlsfcZ7QpSeh6oSJdTPQq5u9tzy3KeSTwCF7TAw8KUQ9SRvxNYEoix3WWVi9tido/d72XbOyewHoCNewE0+7SzSgABTNps9GHiNPROviRltEnh+gPEFJ2kNw/8yGCPRXZfucoWxHzo87bzTeSt++zdBCHqGDh29fUmRtyGxfZ9j8wR9A8UKoGLMbTyvS+kzDulHY8c7ga17+9XdNWpBfTsxqcA7CNV0bHDCeXBlo86p5BELYoeftACmiiwx5iTCvTz6XdQG+VdGsCjZwDxb/0Uec8qUsJX6rEUhpKVlKQbSPNEzmBpZ6lk38dmAep5FxfNtO/nOqDTcs8Rix37SGSGM+GutEA09PAj28IKHeQV95ojo3mWqHg5v2lsNtPGt9bTDKOXKWb1jK/RjOF1X9+ObtOPniZOp9QhVe3FA+/E3QTEJhnp8halgK8Ys3h3n6e2jx2BER2E8Du6Uid3YVgQCiu1903itPL9Kdq67lDhlYnqQ2ZnoXsP/empRB27jJcSpO3Zdqo4w/kvW/BpcFX4bk2hZ1o6PZyZDB1ogqgqzNOamjIj79BSlalCTmeTOmLRO7c
MIME-Version: 1.0

<meta http-equiv=3D"Content-Type" content=3D"text/html; charset=3Dutf-8"><p=
 style=3D"margin-top:2px;margin-bottom:2px;">Dear sir,</p><p style=3D"margi=
n-top:2px;margin-bottom:2px;"><br></p><p style=3D"margin-top:2px;margin-bot=
tom:2px;">Yingxinyuan Int'l(Group) Ltd. is top electronic components in Chi=
na, our main=20
customer including USA=E3=80=81Germany=E3=80=81Russia=E3=80=81France=E3=80=
=81Brazil=E3=80=81Korea .<br><span style=3D"color:#FFF;font-size:10px;"><em=
>though he was quite sure no local people would steal from him, </em></span=
></p><p style=3D"margin-top:2px;margin-bottom:2px;">We offer good=20
price and &nbsp;120 days quality guarantee, are you interested to get our c=
atalog=20
with pricelist?</p><p style=3D"margin-top:2px;margin-bottom:2px;">Best Rega=
rds /Linda<br><span style=3D"color:#FFF;font-size:10px;"><em>There was only=
 the heavy sharp blue head and the big eyes and the clicking, thrusting all=
-swallowing jaws.</em></span></p><p style=3D"margin-top:2px;margin-bottom:2=
px;">Yingxinyuan Int'l(Group) Ltd. &nbsp; <br>We are 14=20
years' STRC and QAP member on=20
HKiventory<br>A418, Overseas Decoration Bldg., Huafu Rd., Futian Dist., She=
nzhen 518031, CN<br>Phone: 86-755-83247000-6210=20
ext &nbsp;2008 &nbsp; Fax: 86-755-83342111/83240615 <br></p><p><br></p><p><=
br></p><p><br></p><p><br></p><p><br></p><p><br></p><p><br></p><p><span styl=
e=3D"color:#FFF;font-size:10px;"><em>Mrs. Bennet wondered at their coming, =
and thought them very wrong to give so much trouble, and was sure Jane woul=
d have caught cold again.</em></span></p><p><br></p><p><span style=3D"color=
:#FFF;font-size:10px;"><em>The old man=E2=80=99s head was very old though a=
nd with his eyes closed there was no life in his face. </em></span></p><p><=
span style=3D"color:#FFF;font-size:10px;"><em>The moon affects her as it do=
es a woman, he thought.</em></span></p><p><span style=3D"color:#FFF;font-si=
ze:10px;"><em>and now burning pamphlets at the door of Westminster Hall; to=
day, taking the life of an atrocious murderer, </em></span></p>
